<h1>Testing Notebook</h1>
The purpose of this notebook is to test the chatbot's responses on chatlog data :)

## Set up

In [1]:
# import libraries and modules
from chatbot.Narelle import Narelle
import pprint
import pandas as pd
import json
import os

In [2]:
# Initialise chatbot
bot = Narelle()

/Users/bern/Documents/GitHub/fyp-chatbot/src/knowledge_base_manager/knowledge_base_manager/core/database_manager.py:17: UserWarning: You appear to be connected to a CosmosDB cluster. For more information regarding feature compatibility and support please visit https://www.mongodb.com/supportability/cosmosdb
  self.client = pymongo.MongoClient(db_connection_str)

### Import chatlog

In [3]:
# Function to take in a json object and print in JSON-structured format
def print_json(data, indent=2):
    output = json.dumps(data, indent=indent)
    print(output)

In [4]:
# Import chatlog data

# Load plain text file and reconstruct the JSON object
chatlogfile = "/Users/bern/Documents/FYP/[CONFIDENTIAL] Chatlog and test documents/chatlog/chatlog.json"

with open(chatlogfile, 'r') as f:
    chatlog = json.load(f)

## Observe the data structure
print_json(chatlog)

{
  "chatlog": [
    {
      "_id": {
        "$oid": "65f172e8192f78bab2a94539"
      },
      "stime": {
        "text": "2024-03-13 17:33:28",
        "timestamp": 1710322408.501202
      },
      "messages": [
        {
          "role": "user",
          "content": "is there lab next week?",
          "recorded_on": {
            "text": "2024-03-13 17:33:56",
            "timestamp": 1710322436.547978
          }
        },
        {
          "role": "ai",
          "content": "There will be no lab session next week as it is Recess Week. \n\n\n **Sources:** *['FAQs about the Course', 'Course Calendar', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:34:03",
            "timestamp": 1710322443.800639
          },
          "token_cost": {
            "cost": "0.00392550",
            "tokens": 2612
          }
        },
        {
          "role": "user",
          "content": "what week is it now",
          "recorded_on": {
            "text": "2024-03-13 17:34:21",
            "timestamp": 1710322461.171272
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, I don't have access to real-time information. Could you please check the course calendar or NTULearn to confirm which week it is currently? ",
          "recorded_on": {
            "text": "2024-03-13 17:34:25",
            "timestamp": 1710322465.632266
          },
          "token_cost": {
            "cost": "0.00417000",
            "tokens": 2769
          }
        },
        {
          "role": "user",
          "content": "what is the deadline for my assignment",
          "recorded_on": {
            "text": "2024-03-13 17:34:54",
            "timestamp": 1710322494.562975
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, I don't have access to real-time information about your specific assignment deadline. Please check the assignment details and instructions provided by your instructor on NTULearn or in class to confirm the deadline. If you are unable to find the deadline, you can email your instructor for clarification. ",
          "recorded_on": {
            "text": "2024-03-13 17:35:05",
            "timestamp": 1710322505.071112
          },
          "token_cost": {
            "cost": "0.00403300",
            "tokens": 2669
          }
        },
        {
          "role": "user",
          "content": "what is the deadline for my assignment",
          "recorded_on": {
            "text": "2024-03-13 17:35:12",
            "timestamp": 1710322512.711009
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, I don't have access to real-time information about your specific assignment deadline. Please check the assignment details and instructions provided by your instructor on NTULearn or in class to confirm the deadline. If you are unable to find the deadline, you can email your instructor for clarification. ",
          "recorded_on": {
            "text": "2024-03-13 17:35:18",
            "timestamp": 1710322518.225166
          },
          "token_cost": {
            "cost": "0.00414700",
            "tokens": 2745
          }
        }
      ],
      "last_interact": {
        "text": "2024-03-13 17:35:18",
        "timestamp": 1710322518.225371
      },
      "llm_deployment_name": "asknarelle-experimental-gpt-35-turbo",
      "llm_model_name": "gpt-3.5-turbo-instruct",
      "vectorstore_index": "vector-sc1015-ay23t2-b",
      "overall_cost": {
        "overall_cost": 0.0162755,
        "overall_tokens": 10795
      },
      "Person": "44793f1faad064b52f6716c2c4b0633e"
    },
    {
      "_id": {
        "$oid": "65f17301192f78bab2a9453c"
      },
      "stime": {
        "text": "2024-03-13 17:33:53",
        "timestamp": 1710322433.863411
      },
      "messages": [
        {
          "role": "user",
          "content": "what type of questions will I get in the AI theory quiz?",
          "recorded_on": {
            "text": "2024-03-13 17:35:09",
            "timestamp": 1710322509.178527
          }
        },
        {
          "role": "ai",
          "content": "The AI theory quiz will consist of multiple-choice questions and other objective types such as fill in the blanks and numeric questions. The questions will be based on the lectures and related theory covered in the course. The specific details and arrangements for the quiz will be announced a week before the quiz. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Quiz Page', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:35:16",
            "timestamp": 1710322516.881127
          },
          "token_cost": {
            "cost": "0.00466950",
            "tokens": 3094
          }
        },
        {
          "role": "user",
          "content": "how should I study for the quiz",
          "recorded_on": {
            "text": "2024-03-13 17:36:03",
            "timestamp": 1710322563.735932
          }
        },
        {
          "role": "ai",
          "content": "To prepare for the AI theory quiz, you should review the lecture notes, slides, and any additional materials provided by the instructor. You can also review the textbook and practice problems related to the topics covered in the course. It is also recommended to attend review sessions and ask questions to clarify any doubts. Additionally, you can take the sample theory quiz provided by the instructor to get a feel for the types of questions that may be asked. Finally, make sure to manage your time well and practice answering questions under timed conditions to improve your speed and accuracy. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Quiz Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:36:10",
            "timestamp": 1710322570.595196
          },
          "token_cost": {
            "cost": "0.00359950",
            "tokens": 2363
          }
        }
      ],
      "last_interact": {
        "text": "2024-03-13 17:36:10",
        "timestamp": 1710322570.595373
      },
      "llm_deployment_name": "asknarelle-experimental-gpt-35-turbo",
      "llm_model_name": "gpt-3.5-turbo-instruct",
      "vectorstore_index": "vector-sc1015-ay23t2-b",
      "overall_cost": {
        "overall_cost": 0.008269,
        "overall_tokens": 5457
      },
      "Person": "c8fc811f7e15b5b900d29071525198e1"
    },
    {
      "_id": {
        "$oid": "65f17302192f78bab2a9453d"
      },
      "stime": {
        "text": "2024-03-13 17:33:54",
        "timestamp": 1710322434.461673
      },
      "messages": [
        {
          "role": "user",
          "content": "when is my lab session?",
          "recorded_on": {
            "text": "2024-03-13 17:34:22",
            "timestamp": 1710322462.180735
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, I don't have access to your specific lab session schedule. Please check the course calendar or the Lab Sessions section on the NTULearn course site for your lab session schedule. ",
          "recorded_on": {
            "text": "2024-03-13 17:34:28",
            "timestamp": 1710322468.888819
          },
          "token_cost": {
            "cost": "0.00368250",
            "tokens": 2442
          }
        },
        {
          "role": "user",
          "content": "when is exercise 5 due?",
          "recorded_on": {
            "text": "2024-03-13 17:35:52",
            "timestamp": 1710322552.957759
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, I don't have that information. The due date for Exercise 5 should be mentioned in the exercise instructions or announced by your course instructor or TA. Please check the NTULearn course site or ask your TA for the deadline. ",
          "recorded_on": {
            "text": "2024-03-13 17:35:57",
            "timestamp": 1710322557.678365
          },
          "token_cost": {
            "cost": "0.00409750",
            "tokens": 2715
          }
        },
        {
          "role": "user",
          "content": "summarise module 1 of Artificial Intelligence",
          "recorded_on": {
            "text": "2024-03-13 17:36:38",
            "timestamp": 1710322598.194305
          }
        },
        {
          "role": "ai",
          "content": "Module 1 of Artificial Intelligence covers the introduction and state-of-the-art of AI. It is one of the four modules that will be assessed during the AI Theory Quiz at the end of the course. Students are advised to complete at least one module per week to catch up with the review lecture and lab exercises for AI. There will be four review lectures for AI which will be conducted on 13, 20, and 27 March as well as 3 April respectively. The lab exercises for AI will be released progressively. \n\n\n **Sources:** *['SC1015_BasicInformation', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:36:44",
            "timestamp": 1710322604.053972
          },
          "token_cost": {
            "cost": "0.00413400",
            "tokens": 2721
          }
        }
      ],
      "last_interact": {
        "text": "2024-03-13 17:36:44",
        "timestamp": 1710322604.054161
      },
      "llm_deployment_name": "asknarelle-experimental-gpt-35-turbo",
      "llm_model_name": "gpt-3.5-turbo-instruct",
      "vectorstore_index": "vector-sc1015-ay23t2-b",
      "overall_cost": {
        "overall_cost": 0.011914000000000001,
        "overall_tokens": 7878
      },
      "Person": "4d35cc73b0080c4e10307266d68738ff"
    },
    {
      "_id": {
        "$oid": "65f17307192f78bab2a9453f"
      },
      "stime": {
        "text": "2024-03-13 17:33:59",
        "timestamp": 1710322439.617128
      },
      "messages": [
        {
          "role": "user",
          "content": "When is the AI Quiz?",
          "recorded_on": {
            "text": "2024-03-13 17:34:40",
            "timestamp": 1710322480.785272
          }
        },
        {
          "role": "ai",
          "content": "The AI Theory Quiz will be conducted during Week 14 of the course. The specific date and time slots will be announced closer to the date. The quiz will be conducted physically at the lab using the Lockdown Browser. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:34:49",
            "timestamp": 1710322489.399618
          },
          "token_cost": {
            "cost": "0.00354400",
            "tokens": 2348
          }
        },
        {
          "role": "user",
          "content": "When is the AI Quiz?",
          "recorded_on": {
            "text": "2024-03-13 17:35:07",
            "timestamp": 1710322507.976449
          }
        },
        {
          "role": "ai",
          "content": "The AI Theory Quiz will be conducted during Week 14 of the course. The specific date and time slots will be announced closer to the date. The quiz will be conducted physically at the lab using the Lockdown Browser. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:35:14",
            "timestamp": 1710322514.836385
          },
          "token_cost": {
            "cost": "0.00363400",
            "tokens": 2408
          }
        },
        {
          "role": "user",
          "content": "When will the DS Quiz results be released?",
          "recorded_on": {
            "text": "2024-03-13 17:35:56",
            "timestamp": 1710322556.181706
          }
        },
        {
          "role": "ai",
          "content": "The marks for the DS Theory Quiz, along with the LAMS and Lab Exercise marks, will be disclosed during the semester. So, you can expect to know your marks for the DS Quiz sometime during the semester. However, the exact date is not mentioned in the information provided. You can check with your course instructor or TA for more information. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Quiz Page', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:36:03",
            "timestamp": 1710322563.720171
          },
          "token_cost": {
            "cost": "0.00478500",
            "tokens": 3167
          }
        },
        {
          "role": "user",
          "content": "What is the DS Quiz average usually?",
          "recorded_on": {
            "text": "2024-03-13 17:36:28",
            "timestamp": 1710322588.019884
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, but I do not have access to the information about the average score for the DS Quiz. The average score may vary from year to year, depending on the performance of the students. However, you can check with your course instructor or TA for more information. ",
          "recorded_on": {
            "text": "2024-03-13 17:36:35",
            "timestamp": 1710322595.768517
          },
          "token_cost": {
            "cost": "0.00441500",
            "tokens": 2925
          }
        },
        {
          "role": "user",
          "content": "Thank you very much!",
          "recorded_on": {
            "text": "2024-03-13 17:36:51",
            "timestamp": 1710322611.509901
          }
        },
        {
          "role": "ai",
          "content": "You're welcome! If you have any more questions, feel free to ask. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Quiz Page', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:36:55",
            "timestamp": 1710322615.856365
          },
          "token_cost": {
            "cost": "0.00315650",
            "tokens": 2099
          }
        }
      ],
      "last_interact": {
        "text": "2024-03-13 17:36:55",
        "timestamp": 1710322615.856571
      },
      "llm_deployment_name": "asknarelle-experimental-gpt-35-turbo",
      "llm_model_name": "gpt-3.5-turbo-instruct",
      "vectorstore_index": "vector-sc1015-ay23t2-b",
      "overall_cost": {
        "overall_cost": 0.019534500000000003,
        "overall_tokens": 12947
      },
      "Person": "4d3fe7a9fcf8a8bb1c037a510ee979f7"
    },
    {
      "_id": {
        "$oid": "65f17325192f78bab2a94542"
      },
      "stime": {
        "text": "2024-03-13 17:34:29",
        "timestamp": 1710322469.553527
      },
      "messages": [],
      "last_interact": {
        "text": "2024-03-13 17:34:29",
        "timestamp": 1710322469.553747
      },
      "llm_deployment_name": "asknarelle-experimental-gpt-35-turbo",
      "llm_model_name": "gpt-3.5-turbo-instruct",
      "vectorstore_index": "vector-sc1015-ay23t2-b",
      "Person": "f56b88bd671c3c245ec48a8973add8ed"
    },
    {
      "_id": {
        "$oid": "65f17326192f78bab2a94544"
      },
      "stime": {
        "text": "2024-03-13 17:34:30",
        "timestamp": 1710322470.072647
      },
      "messages": [
        {
          "role": "user",
          "content": "hello",
          "recorded_on": {
            "text": "2024-03-13 17:34:41",
            "timestamp": 1710322481.39032
          }
        },
        {
          "role": "ai",
          "content": "Hello! How can I assist you today? \n\n\n **Sources:** *['NTU Learn - Quiz Page', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:34:48",
            "timestamp": 1710322488.594567
          },
          "token_cost": {
            "cost": "0.00300750",
            "tokens": 2002
          }
        },
        {
          "role": "user",
          "content": "when is the final quiz for 1015?",
          "recorded_on": {
            "text": "2024-03-13 17:35:00",
            "timestamp": 1710322500.14842
          }
        },
        {
          "role": "ai",
          "content": "There is no final quiz for SC1015/CE1115/CZ1115. However, there are two theory quizzes during the semester, one for Data Science (DS) and one for Artificial Intelligence (AI). The DS theory quiz will take place during the Recess Week on Friday, 8 March, and the AI theory quiz will take place during Week 14. The specific slots for the quizzes will be set closer to the dates, and the entire batch will take the quizzes on the same day to ensure fairness across the class. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Quiz Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:35:09",
            "timestamp": 1710322509.418495
          },
          "token_cost": {
            "cost": "0.00420050",
            "tokens": 2764
          }
        }
      ],
      "last_interact": {
        "text": "2024-03-13 17:35:09",
        "timestamp": 1710322509.418657
      },
      "llm_deployment_name": "asknarelle-experimental-gpt-35-turbo",
      "llm_model_name": "gpt-3.5-turbo-instruct",
      "vectorstore_index": "vector-sc1015-ay23t2-b",
      "overall_cost": {
        "overall_cost": 0.007208000000000001,
        "overall_tokens": 4766
      },
      "Person": "9503c7e66f97cb021f66cce6082b19bb"
    },
    {
      "_id": {
        "$oid": "65f17329192f78bab2a94545"
      },
      "stime": {
        "text": "2024-03-13 17:34:33",
        "timestamp": 1710322473.090412
      },
      "messages": [
        {
          "role": "user",
          "content": "hello",
          "recorded_on": {
            "text": "2024-03-13 17:34:50",
            "timestamp": 1710322490.680542
          }
        },
        {
          "role": "ai",
          "content": "Hello! How can I assist you today? \n\n\n **Sources:** *['NTU Learn - Quiz Page', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:35:03",
            "timestamp": 1710322503.714181
          },
          "token_cost": {
            "cost": "0.00300750",
            "tokens": 2002
          }
        },
        {
          "role": "user",
          "content": "hi",
          "recorded_on": {
            "text": "2024-03-13 17:35:12",
            "timestamp": 1710322512.128185
          }
        },
        {
          "role": "ai",
          "content": "Hello! How can I assist you today? \n\n\n **Sources:** *['NTU Learn - Quiz Page', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:35:16",
            "timestamp": 1710322516.888624
          },
          "token_cost": {
            "cost": "0.00303750",
            "tokens": 2022
          }
        },
        {
          "role": "user",
          "content": "give me a summary of the AI part of the module",
          "recorded_on": {
            "text": "2024-03-13 17:35:42",
            "timestamp": 1710322542.539723
          }
        },
        {
          "role": "ai",
          "content": "Sure! The AI part of the module covers four main topics:\n\n1. Introduction and State-of-the-Art\n2. Intelligent Agents\n3. Solving Problems by Search\n4. Constraint Satisfaction and Game Playing\n\nBy the end of the AI part of the course, you should be able to understand the roles and requirements of artificial intelligence in practical applications, apply basic artificial intelligence techniques in search problems and game playing, and discuss and explain concepts of computer vision and natural language processing. These topics will be assessed during the AI Theory Quiz (25%) at the end of the course. \n\n\n **Sources:** *['SC1015_BasicInformation', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:35:52",
            "timestamp": 1710322552.19523
          },
          "token_cost": {
            "cost": "0.00363750",
            "tokens": 2386
          }
        },

In [14]:
# view chatlog
chatlog['chatlog'][108]

{'_id': {'$oid': '65fa4e6f6090ad0b74002bf3'},
 'stime': {'text': '2024-03-20 10:48:15', 'timestamp': 1710902895.371987},
 'messages': [{'role': 'user',
   'content': 'Hi Narelle :)',
   'recorded_on': {'text': '2024-03-20 10:48:40',
    'timestamp': 1710902920.173479}},
  {'role': 'ai',
   'content': "Hello! How can I assist you today? \n\n\n **Sources:** *['Course Information', 'FAQs about the Course', 'NTU Learn - Announcements Page']*",
   'recorded_on': {'text': '2024-03-20 10:48:45',
    'timestamp': 1710902925.067538},
   'token_cost': {'cost': '0.00296550', 'tokens': 1974}},
  {'role': 'user',
   'content': 'How were you programmed?',
   'recorded_on': {'text': '2024-03-20 10:48:55',
    'timestamp': 1710902935.104551}},
  {'role': 'ai',
   'content': "I was programmed using natural language processing (NLP) techniques and machine learning algorithms. My developers used Python programming language and various libraries such as NLTK, spaCy, and TensorFlow to build my conversational abilities. They also trained me on a large dataset of conversations to improve my responses and make me more accurate. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Announcements Page', 'NTU Learn - Mini Project Page']*",
   'recorded_on': {'text': '2024-03-20 10:48:59',
    'timestamp': 1710902939.479759},
   'token_cost': {'cost': '0.00330150', 'tokens': 2180}},
  {'role': 'user',
   'content': "That's great! How can I help?",
   'recorded_on': {'text': '2024-03-20 10:49:17',
    'timestamp': 1710902957.161853}},
  {'role': 'ai',
   'content': "I'm glad you're willing to help! Is there anything specific you would like to contribute to the course or the chatbot development? If you're interested in RAG-based chatbot development, you can join the lecturer's team during the semester break (May-July 2024) to learn more and gain some experience with LLM & RAG. You can also email the course instructors or lab TAs if you have any questions or doubts regarding the course material. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Announcements Page', 'NTU Learn - Mini Project Page']*",
   'recorded_on': {'text': '2024-03-20 10:49:21',
    'timestamp': 1710902961.275046},
   'token_cost': {'cost': '0.00324100', 'tokens': 2129}}],
 'last_interact': {'text': '2024-03-20 10:49:21',
  'timestamp': 1710902961.275295},
 'llm_deployment_name': 'asknarelle-experimental-gpt-35-turbo',
 'llm_model_name': 'gpt-3.5-turbo-instruct',
 'vectorstore_index': 'vector-sc1015-ay23t2-b',
 'overall_cost': {'overall_cost': 0.009507999999999999,
  'overall_tokens': 6283},
 'Person': '078a1b84005e3417f28792bcd0d80b2b'}

## Samples

In [5]:
# simple query
query = "What is the course content?"

response = bot.answer_this(query)

print("\nQuery: ", query)
print("\nResponse: "+response["chatbot_response"])
print("\nContext: ", response["context"])
print("\nCost: ", response["cost"])
print("\nTokens: ", response["tokens"])

2025-02-08 10:28:41,953 - chatbot.Narelle - INFO - =======[LLM COST] total cost: 1.4249999999999997e-05; total tokens: 50
2025-02-08 10:28:41,954 - chatbot.Narelle - INFO -

===== CONTEXT FOR QUERY 'What is the course content?' =====

Question: Is a calculator required for the mini project?
Answer: No, you do not need a calculator for the mini project

Question: What steps should I follow to arrange a make-up class with the lecturer?
Answer: You may not arrange a make-up class with the lecturer, the resources needed to catch up are on NTULearn

Question: Will there be a make-up lesson with the lecturer if I am unable to attend class?
Answer: No there will be no make-up lessons for this course.

Question: What should I do if I can't attend the lecture?
Answer: You may catch up with course content on NTULearn.

Question: What calculator model am I allowed to use for the exam?
Answer: You may use any scientific calculator for the exam. However, no graphic calculator is allowed.

---------------
Course Resources

There is no single textbook for this course. We will follow the references from time to time. Additional resources, if required, will be shared with you in the Lectures and/or in the Lab.

References

Python Data Science Handbook by Jake Vanderplas (https://jakevdp.github.io/PythonDataScienceHandbook/)

An Introduction to Statistical Learning by James, Witten, Hastie, Tibshirani (https://statlearning.com/)

Artificial Intelligence: A Modern Approach by Stuart Russell and Peter Norvig (http://aima.cs.berkeley.edu/)

Course and Lab Instructors

Dr Smitha K G, Senior Lecturer, SCSE, and Mr. Ong Chin Ann, Lecturer , SCSE are the Instructors for this course.  You will also interact with them during the Review sessions. Dr Smitha K G  (smitha@ntu.edu.sg) is the Course Coordinator.

Please note that your LAMS sequences were earlier prepared by Dr. Sourav Sen Gupta (DS) and Prof. Bo. An (AI).

Course Instructors

Dr Smitha K G (Co-Ord) and Mr. Ong Chin Ann

smitha@ntu.edu.sg

chinann.ong@ntu.edu.sg

Office : N4-02c-75

Office : N4-02c-108

---------------
Course Information

‘Data’ is the new driving force, provided we know how to extract relevant ‘Intelligence’.

This course will start with the core principles of Data Science, and will equip you with the basic tools and techniques of data handling, exploratory data analysis, data visualization, data-based inference, and data-focussed communication. The course will also introduce you to the fundamentals of Artificial Intelligence – state space, search problems, computer vision and natural language processing.

The course will motivate you to work closely with data and make data-driven decisions in your field of study. The course will also touch upon ethical issues in Data Science and Artificial Intelligence, and motivate you to explore the cutting-edge applications related to Big Data, Neural Networks and Deep Learning. Python will be the language of choice to introduce hands-on computational techniques.

---------------
The course will motivate you to work closely with data and make data-driven decisions in your field of study. The course will also touch upon ethical issues in Data Science and Artificial Intelligence, and motivate you to explore the cutting-edge applications related to Big Data, Neural Networks and Deep Learning. Python will be the language of choice to introduce hands-on computational techniques.

By the end of this course, you should be able to identify and define data-oriented problems and data-driven decisions in real life, discuss and illustrate the problems in terms of data exploration and visualization, apply basic machine learning tools to extract inferential information from the data, compose an engaging “data-story” to communicate the problem and the inference, outline the roles and requirements of artificial intelligence in practical applications, apply basic artificial intelligence techniques in search problems and game playing, and discuss and explain concepts of computer vision and natural language processing.

Course Resources

There is no single textbook for this course. We will follow the references from time to time. Additional resources, if required, will be shared with you in the Lectures and/or in the Lab.

References

Python Data Science Handbook by Jake Vanderplas (https://jakevdp.github.io/PythonDataScienceHandbook/)

An Introduction to Statistical Learning by James, Witten, Hastie, Tibshirani (https://statlearning.com/)

---------------
Hence, we encourage and welcome all of you to try it out when you have questions regarding the course. In other words, when you have question(s) about the course, you can try to ask "Narelle" first, before approaching/emailing your TA or Instructor. You can also help us to evaluate the relevancy/correctness of the responses by pressing the "Thumbs Up/Down" under each response. Do tell us what you think about the chatbot a few weeks later after you have interacted with the chatbot or when you come across some error with the chatbot by clicking the "Feedback" button on the left panel, we will look into it and fix it.

Do note that at present time, we have not fed "Narelle" with any course contents e.g. textbook or lecture slides/materials used in this course. But you can give it a try by asking questions related to the course syllabus/content to see how it behaves/responds (we are also interested to know how it behaves too :) ). Do read through the remote informed consent and terms of use before using the Chatbot.

Getting Involved in the Research & Development for AskNarelle - Ungraded Activity
===================

2025-02-08 10:28:41,954 - chatbot.Narelle - INFO - Rephrased query: Sure! Please provide the latest user query you'd like me to rephrase.
2025-02-08 10:28:44,250 - chatbot.Narelle - INFO - =======[LLM COST] total cost: 0.00031455; total tokens: 1611

Query:  What is the course content?

Response: The course SC1015 Introduction to Data Science and Artificial Intelligence covers the following content:

1. Core principles of Data Science, including:
   - Data handling
   - Exploratory data analysis
   - Data visualization
   - Data-based inference
   - Data-focussed communication

2. Fundamentals of Artificial Intelligence, including:
   - State space
   - Search problems
   - Computer vision
   - Natural language processing

3. Ethical issues in Data Science and Artificial Intelligence.

4. Applications related to Big Data, Neural Networks, and Deep Learning.

5. Hands-on computational techniques using Python.

By the end of the course, you should be able to identify and define data-oriented problems, apply basic machine learning tools, compose engaging data stories, and discuss concepts of AI in practical applications.

Context:  Question: Is a calculator required for the mini project?
Answer: No, you do not need a calculator for the mini project

Question: What steps should I follow to arrange a make-up class with the lecturer?
Answer: You may not arrange a make-up class with the lecturer, the resources needed to catch up are on NTULearn

Question: Will there be a make-up lesson with the lecturer if I am unable to attend class?
Answer: No there will be no make-up lessons for this course.

Question: What should I do if I can't attend the lecture?
Answer: You may catch up with course content on NTULearn.

Question: What calculator model am I allowed to use for the exam?
Answer: You may use any scientific calculator for the exam. However, no graphic calculator is allowed.

---------------
Course Resources

There is no single textbook for this course. We will follow the references from time to time. Additional resources, if required, will be shared with you in the Lectures and/or in the Lab.

References

Python Data Science Handbook by Jake Vanderplas (https://jakevdp.github.io/PythonDataScienceHandbook/)

An Introduction to Statistical Learning by James, Witten, Hastie, Tibshirani (https://statlearning.com/)

Artificial Intelligence: A Modern Approach by Stuart Russell and Peter Norvig (http://aima.cs.berkeley.edu/)

Course and Lab Instructors

Dr Smitha K G, Senior Lecturer, SCSE, and Mr. Ong Chin Ann, Lecturer , SCSE are the Instructors for this course.  You will also interact with them during the Review sessions. Dr Smitha K G  (smitha@ntu.edu.sg) is the Course Coordinator.

Please note that your LAMS sequences were earlier prepared by Dr. Sourav Sen Gupta (DS) and Prof. Bo. An (AI).

Course Instructors

Dr Smitha K G (Co-Ord) and Mr. Ong Chin Ann

smitha@ntu.edu.sg

chinann.ong@ntu.edu.sg

Office : N4-02c-75

Office : N4-02c-108

---------------
Course Information

‘Data’ is the new driving force, provided we know how to extract relevant ‘Intelligence’.

This course will start with the core principles of Data Science, and will equip you with the basic tools and techniques of data handling, exploratory data analysis, data visualization, data-based inference, and data-focussed communication. The course will also introduce you to the fundamentals of Artificial Intelligence – state space, search problems, computer vision and natural language processing.

The course will motivate you to work closely with data and make data-driven decisions in your field of study. The course will also touch upon ethical issues in Data Science and Artificial Intelligence, and motivate you to explore the cutting-edge applications related to Big Data, Neural Networks and Deep Learning. Python will be the language of choice to introduce hands-on computational techniques.

---------------
The course will motivate you to work closely with data and make data-driven decisions in your field of study. The course will also touch upon ethical issues in Data Science and Artificial Intelligence, and motivate you to explore the cutting-edge applications related to Big Data, Neural Networks and Deep Learning. Python will be the language of choice to introduce hands-on computational techniques.

By the end of this course, you should be able to identify and define data-oriented problems and data-driven decisions in real life, discuss and illustrate the problems in terms of data exploration and visualization, apply basic machine learning tools to extract inferential information from the data, compose an engaging “data-story” to communicate the problem and the inference, outline the roles and requirements of artificial intelligence in practical applications, apply basic artificial intelligence techniques in search problems and game playing, and discuss and explain concepts of computer vision and natural language processing.

Course Resources

There is no single textbook for this course. We will follow the references from time to time. Additional resources, if required, will be shared with you in the Lectures and/or in the Lab.

References

Python Data Science Handbook by Jake Vanderplas (https://jakevdp.github.io/PythonDataScienceHandbook/)

An Introduction to Statistical Learning by James, Witten, Hastie, Tibshirani (https://statlearning.com/)

---------------
Hence, we encourage and welcome all of you to try it out when you have questions regarding the course. In other words, when you have question(s) about the course, you can try to ask "Narelle" first, before approaching/emailing your TA or Instructor. You can also help us to evaluate the relevancy/correctness of the responses by pressing the "Thumbs Up/Down" under each response. Do tell us what you think about the chatbot a few weeks later after you have interacted with the chatbot or when you come across some error with the chatbot by clicking the "Feedback" button on the left panel, we will look into it and fix it.

Do note that at present time, we have not fed "Narelle" with any course contents e.g. textbook or lecture slides/materials used in this course. But you can give it a try by asking questions related to the course syllabus/content to see how it behaves/responds (we are also interested to know how it behaves too :) ). Do read through the remote informed consent and terms of use before using the Chatbot.

Getting Involved in the Research & Development for AskNarelle - Ungraded Activity

Cost:  0.00031455

Tokens:  1611

In [11]:
sample_conversation = {
      "_id": {
        "$oid": "65f172e8192f78bab2a94539"
      },
      "stime": {
        "text": "2024-03-13 17:33:28",
        "timestamp": 1710322408.501202
      },
      "messages": [
        {
          "role": "user",
          "content": "is there lab next week?",
          "recorded_on": {
            "text": "2024-03-13 17:33:56",
            "timestamp": 1710322436.547978
          }
        },
        {
          "role": "ai",
          "content": "There will be no lab session next week as it is Recess Week. \n\n\n **Sources:** *['FAQs about the Course', 'Course Calendar', 'NTU Learn - Announcements Page']*",
          "recorded_on": {
            "text": "2024-03-13 17:34:03",
            "timestamp": 1710322443.800639
          },
          "token_cost": {
            "cost": "0.00392550",
            "tokens": 2612
          }
        },
        {
          "role": "user",
          "content": "what week is it now",
          "recorded_on": {
            "text": "2024-03-13 17:34:21",
            "timestamp": 1710322461.171272
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, I don't have access to real-time information. Could you please check the course calendar or NTULearn to confirm which week it is currently? ",
          "recorded_on": {
            "text": "2024-03-13 17:34:25",
            "timestamp": 1710322465.632266
          },
          "token_cost": {
            "cost": "0.00417000",
            "tokens": 2769
          }
        },
        {
          "role": "user",
          "content": "what is the deadline for my assignment",
          "recorded_on": {
            "text": "2024-03-13 17:34:54",
            "timestamp": 1710322494.562975
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, I don't have access to real-time information about your specific assignment deadline. Please check the assignment details and instructions provided by your instructor on NTULearn or in class to confirm the deadline. If you are unable to find the deadline, you can email your instructor for clarification. ",
          "recorded_on": {
            "text": "2024-03-13 17:35:05",
            "timestamp": 1710322505.071112
          },
          "token_cost": {
            "cost": "0.00403300",
            "tokens": 2669
          }
        },
        {
          "role": "user",
          "content": "what is the deadline for my assignment",
          "recorded_on": {
            "text": "2024-03-13 17:35:12",
            "timestamp": 1710322512.711009
          }
        },
        {
          "role": "ai",
          "content": "I'm sorry, I don't have access to real-time information about your specific assignment deadline. Please check the assignment details and instructions provided by your instructor on NTULearn or in class to confirm the deadline. If you are unable to find the deadline, you can email your instructor for clarification. ",
          "recorded_on": {
            "text": "2024-03-13 17:35:18",
            "timestamp": 1710322518.225166
          },
          "token_cost": {
            "cost": "0.00414700",
            "tokens": 2745
          }
        }
      ],
      "last_interact": {
        "text": "2024-03-13 17:35:18",
        "timestamp": 1710322518.225371
      },
      "llm_deployment_name": "asknarelle-experimental-gpt-35-turbo",
      "llm_model_name": "gpt-3.5-turbo-instruct",
      "vectorstore_index": "vector-sc1015-ay23t2-b",
      "overall_cost": {
        "overall_cost": 0.0162755,
        "overall_tokens": 10795
      },
      "Person": "44793f1faad064b52f6716c2c4b0633e"
    }

sample_conversations = [sample_conversation]

In [12]:
# printing response and metadata for one conversation
for message in sample_conversation["messages"]:
    if message["role"]=="user":
        # output user's query
        query = message["content"]
        response = bot.answer_this(query=query)

        print("Query: ", query)
        print("Response: "+response["chatbot_response"])
        print("Context: ", response["context"])
        print("Cost: ", response["cost"])
        print("Tokens: ", response["tokens"])
        print()

Query:  is there lab next week?
Response: Based on the information provided, there is no lab session scheduled for next week. The lab session for next week is intended for Mini-Project consultation, so there is no need to rush to complete any lab exercises. It is recommended to use the lab session to work on your mini project and consult your TA. If your mini project is progressing well, you can start working on the lab exercises. If you have any further questions or need clarification, feel free to ask.
Context:  ['I wish you will enjoy the exercise and learn more through it, rather than just attempt it for the marks. As always, I will post the solution after the week 5 and after all submissions end (in case there are extensions).\xa0\n\nPlease note that LABS on Feb 9th is cancelled and will be done on Feb 16th. Affected lab groups please note.\n\nRegards,\nSmitha\n\nDS Theory quiz details , Exercise 4 posted\n\nPosted on: Thursday, February 15, 2024 2:07:10 PM SGT\n\nData Science Theory Quiz details have been posted under "Quizzes" section on NTULearn course site.\xa0The quiz will be held across 2 slots on\xa08 March, Friday: 12:30 pm - 2:00 pm and 2:30 pm - 4:00 pm.\xa0Please check the quiz slot and venue allocation carefully in that information, and come to the designated lab on time. For part time students, the session will be on 8 March, Friday, 7:00 pm - 8:30 pm @HPL.\n\nA make-up session will be held on week 8, 13th March, Wednesday, 4.30 pm - 5:30 pm (lecture hour), only to cater for the exceptional cases. Please refer to Quiz details posted under "Quizzes" tab.\n\nI have posted Exercise 4 (linear Regression) for next week.\xa0 Please feel free to discuss with your friends and your Lab TA if you have any problem.The solution to Exercise 3 and LAMS Quiz Answers for EDA (few more yet to complete the same) will be posted by early next week . I will also post the project details by early next week. \xa0\n\nregards,\n\nSmitha\n\nMini Project details released\n\nPosted on: Monday, February 19, 2024 5:38:22 PM SGT', "I have posted Exercise 4 (linear Regression) for next week.\xa0 Please feel free to discuss with your friends and your Lab TA if you have any problem.The solution to Exercise 3 and LAMS Quiz Answers for EDA (few more yet to complete the same) will be posted by early next week . I will also post the project details by early next week. \xa0\n\nregards,\n\nSmitha\n\nMini Project details released\n\nPosted on: Monday, February 19, 2024 5:38:22 PM SGT\n\nDear Students,\n\nHope you are enjoying Exercise 4 on Linear Regression this week. Please feel free to discuss with your friends and your Lab TA if you have any problem.\n\nWe have released the Mini Project details.\xa0Please check the Mini-Project Tab in NTUlearn Coursesite for more information. I have also suggested a few datasets. You may take a look at them, or find your own.\nFinding your own dataset/problem for your own project is still preferable. Use the suggested data sources only if you can't find any other dataset.\n\nYour Lab TAs will share a google speard sheet with you such that you can formally enter the team for the Mini Project. Please wait for the instructions from your LAB TAs.\xa0\n\nSee you for the review lecture on Wednesday on Classification/ Decision tree. :-)\n\nRegards,\nSmitha\n\nExercise 5 released, sign up sheet for mini project also released via LAB TAs\n\nPosted on: Wednesday, February 21, 2024 3:12:26 PM SGT\n\nDear Students,\n\nI have posted Exercise 5 under Lab Sessions on the NTULearn Course Site. It is on Classification Trees.", 'Next Review Lecture & Lab Exercise 7\n\nLast but not least, we hope to see a higher turn-up rate in the upcoming Review Lecture (same link as the recent one) where I will cover Module 3 & brief the requirements for Lab Exercise 7. The handout will be released a few hours before the session itself. Do join using your NTU Email address so that you do not need to wait in the lobby.\n\nBest Regards & Have a great weekend ahead,\n\nOng Chin Ann\nLecturer | SC1015/CE1115/CZ1115\nchinann.ong@ntu.edu.sg\n\nLab Exercise 7 Released (5%)\n\nPosted on: Wednesday, March 20, 2024 10:13:17 AM SGT\n\nDear Students,\n\nGood Day & Good Morning!!! Just to poke and inform you that the requirements for\xa0Lab Exercise 7 (Graded)\xa0is now released and available under "Lab Session" menu.\n\nDo note that based on course calendar, the Lab Session for this weeks (Week 9) is intended for Mini-Project consultation, hence, there is\xa0no need for you to rush to complete the Lab Exercise 7\xa0on this week itself (because you are given plenty of allowance and time to complete it). You should make use of the lab session this week to work on your mini project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 7.\xa0\n\nDo plan your time and work with your team member effectively to complete this exercise. What I will suggest is:', 'Today, we will talk about some of the main clarifications regarding Decision Trees that you may need to solve Exercise 5 next week.\xa0\n\nThe sign up sheets for min-project is released by your Lab TAs under your lab groups course site. Max size-3 members, Min size=2 members. Please sign up ASAP. If you have difficulty in forming the group, do talk to your TAs. The deadline for you to sign up and form teams is by\xa01st March Friday evening 5pm.\xa0\n\nOnly once the project groups are formed, you can officially start discussing about the same and i can also create peer evaluation portal for same.\n\nSee you today evening for the discussion lecture.\n\nregards\n\nSmitha\n\n[General] Up Next for Part 2 on DSAI!!!!\n\nPosted on: Saturday, March 9, 2024 3:30:00 PM SGT\n\nDear Students,\n\nHope all of you are doing well and are ready to move on to the second part of the course, Artificial Intelligence.\n\nFirst of all, the materials for\xa0Lab Exercise 6: Walk-Through Notebook\xa0(Ungraded) are now available. Do note that\xa0exercise 6\xa0is for your\xa0DS mini-project\xa0and not for the AI.\n\nIn addition to that, the\xa0LAMS Sequence and learning materials for the AI part\xa0are also made available now under the "Course Content" menu for your self-paced learning. The materials for\xa0Lab Exercise 7 (AI Graded Lab)\xa0will be released after next week.\xa0\n\nBelow are the main topics to be covered in the second half of this course :\n\nAI Module 1: Introduction and State-of-the-Art\n\nAI Module 2: Intelligent Agents', 'In addition to that, the\xa0LAMS Sequence and learning materials for the AI part\xa0are also made available now under the "Course Content" menu for your self-paced learning. The materials for\xa0Lab Exercise 7 (AI Graded Lab)\xa0will be released after next week.\xa0\n\nBelow are the main topics to be covered in the second half of this course :\n\nAI Module 1: Introduction and State-of-the-Art\n\nAI Module 2: Intelligent Agents\n\nAI Module 3: Solving Problems by Search\n\nAI Module 4: Constraint Satisfaction and Game Playing\n\nDo note that these topics (AI Module 1- 4) will be assessed during the\xa0AI Theory Quiz (25%)\xa0at the end of the course.\nYou are advised to complete at least one module per week to catch up with the review lecture and lab exercises for AI.\xa0\nThere will be only\xa04 review lectures\xa0for AI which will be conducted on\xa013, 20, and 27 March\xa0as well as\xa03 April\xa0respectively. MS Team link will be announced at NTU Learn on the day itself. Lab Exercises for AI will be released progressively.']
Cost:  0.0033815
Tokens:  2223

Query:  what week is it now
Response: Today's date is 2024-09-19. Based on the information provided, we are currently in Week 14, which started from 22 April 2024. If you have any more questions or need further assistance, feel free to ask!
Context:  ['Next Review Lecture & Lab Exercise 7\n\nLast but not least, we hope to see a higher turn-up rate in the upcoming Review Lecture (same link as the recent one) where I will cover Module 3 & brief the requirements for Lab Exercise 7. The handout will be released a few hours before the session itself. Do join using your NTU Email address so that you do not need to wait in the lobby.\n\nBest Regards & Have a great weekend ahead,\n\nOng Chin Ann\nLecturer | SC1015/CE1115/CZ1115\nchinann.ong@ntu.edu.sg\n\nLab Exercise 7 Released (5%)\n\nPosted on: Wednesday, March 20, 2024 10:13:17 AM SGT\n\nDear Students,\n\nGood Day & Good Morning!!! Just to poke and inform you that the requirements for\xa0Lab Exercise 7 (Graded)\xa0is now released and available under "Lab Session" menu.\n\nDo note that based on course calendar, the Lab Session for this weeks (Week 9) is intended for Mini-Project consultation, hence, there is\xa0no need for you to rush to complete the Lab Exercise 7\xa0on this week itself (because you are given plenty of allowance and time to complete it). You should make use of the lab session this week to work on your mini project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 7.\xa0\n\nDo plan your time and work with your team member effectively to complete this exercise. What I will suggest is:', "You MUST mention which dataset(s) you used, and what EXACTLY is your problem definition.\n\nThis is your chance to explain your MOTIVATION. Don't get carried away; be precise and clear.\n\nNext 3 minutes (approx.)\xa0of your presentation --\xa0Set The Stage\n\nPresent your Exploratory Data Analysis and some initial data-driven Insights from the dataset.\n\nYou MAY also mention how you are planning to set up the Analysis / ML problem for this case.\n\nYou MUST mention how you collected / curated / cleaned / prepared the data for this problem.\n\nDid you only use tools and techniques learned in this course? What ELSE did you learn / try?\n\nNext 3 minutes (approx.)\xa0of your presentation --\xa0Core Analysis\n\nIf you used ML (regression, classification, or something else); mention mainly WHICH one(s).\n\nYou may now briefly CLARIFY why and how the ML problem(s) aim(s) to solve your objective.\n\nHow did you apply ML technique(s) to SOLVE your problem? Which model(s), how and why?\n\nDid you only use tools and techniques learned in this course? What ELSE did you learn / try?\n\nLast 2 minutes (approx.)\xa0of your presentation --\xa0Finish Strong\n\nWhat is the OUTCOME of your project? Did it solve your original problem? Anything interesting?\n\nWhat are your data-driven INSIGHTS and recommendations / views towards the target problem?\n\nEverything you plan to showcase should be presented within the 10 mins. Plan carefully and smartly.", 'P/S: For subsequent Review Lecture in Week 10 & 11, we will be using the same link.\n\nSee you all later, the more the merrier.\n\n\xa0\n\nBest Regards,\n\nOng Chin Ann\nLecturer (SC1015/CE1115/CZ1115)\nemail: chinann.ong@ntu.edu.sg\n\nDS quiz score released\n\nPosted on: Thursday, March 21, 2024 10:00:44 AM SGT\n\nDear Students,\n\nI have released the marks for DS Theory Quiz. The statistics are as follows.\n\nCount : 984 \xa0| \xa0Total marks : 30 \xa0| \xa0Mean : 18.93 \xa0| \xa0Median : 19.25 \xa0| \xa0StdDev : 4.33 \xa0| \xa0Max : 29.5 \xa0| \xa0Min : 3.5\xa0| \xa0Q1 : 16.25 \xa0| \xa0Q3 : 22\n\nIf you have any queries on your marks/quiz feel free to meet me in my office. Queries through email will not be entertained.\n\nRegards,\nSmitha\n\nLab Exercise 8 Released (5%)\n\nPosted on: Wednesday, April 3, 2024 9:06:35 AM SGT\n\nDear Students,\n\nGood Day & Good Morning!!!\n\nJust to post & inform you that the requirements for\xa0Lab Exercise 8 (Graded)\xa0is now released and available under the "Lab Session" menu.\n\nDo note that based on the course calendar, the Lab Session for this week (Week 11) is intended for Mini-Project consultation, hence, you are advise to make use of the lab session this week to work on your mini-project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 8.\xa0\n\nDo plan your time and work with your team members effectively to complete this exercise. What I will suggest is:', 'Q2.7 : Can I get an extension for the LAMS quizzes? I missed it because ...\n\nA : Really sorry. No extension for the LAMS embedded quizzes beyond the deadline, unless your case is truly exceptional. Feel free to send me an email if you think so, but please do note that in most common cases of missing the deadline, it will not be considered. Please try to finish the quizzes within the deadline, or much ahead of time, if possible, so that there is no last minute issue with submission, network outage or sync issues on NTULearn. Anyway, your deadlines are set to coincide with the theory quizzes, and under all practical circumstances, you should complete the LAMS quizzes during revision for your theory quizzes. So, I do not think you want to miss the deadlines. ;-)\n\nFAQs regarding Labs Sessions\n\nQ3.1 : What is the schedule for the Lab Sessions? My NTU calendar says something different.\n\nA : Lab Sessions will happen every week (almost), throughout the semester, and you will generally complete hand-on programming exercises (and some related discussions) during the sessions. They will be held at the Labs. Please check our Course Calendar for the final lab schedule, irrespective of what is mentioned in your NTU calendar. For example : There is no Lab Session in Week 1 or Week 5(the CNY week) and Week 13 (last week of classes).\n\nQ3.2 : What will we actually do in the Lab Sessions?', "Generally, every team should be a 3-member team. You can form 2-member teams only if your Lab Group is not a clean multiple of 3. Please talk to your Lab TA to finalize the project group. They will collect the exact project team information from you in Week 8, after the Recess Week. So you have time to decide on your group.\n\nEven if it's tempting, you can't unfortunately team-up with your Lab TA or with the Course Instructors. We have our own project groups. ;-)\n\nQ5.3 : What if I can't find a team? What if I don't have any friend in my Lab?\n\nA : Please talk to the Lab TA in such a case. They will help you pair up with teams that have 2 (TWO) members or less. Teams are not supposed to have 2 (TWO) members unless it is required for the Lab Group where the total number of students is not a clean multiple of 3. By Week 8, you and/or your TA will surely be able to find you a project team if you can't get it by yourself. Don't worry. Note that team of 4 (FOUR) members will not be allowed.\xa0\n\nQ5.4 : Does the Mini-Project test on Data Science or Artificial Intelligence too?"]
Cost:  0.0032405000000000003
Tokens:  2143

Query:  what is the deadline for my assignment
Response: I'm sorry, I couldn't find specific information about the deadline for your assignment in the provided context. I recommend checking the course outline, the assignment brief, or contacting your course instructor for the exact deadline. If you have any other questions or need further assistance, feel free to ask!

In [13]:
results = []
message_counter = 1
# printing response and metadata for one conversation
for message in sample_conversation["messages"]:
    if message["role"]=="user":
        # output user's query
        query = message["content"]
        result = bot.answer_this(query=query)
        
        result.update({"query":query, "order": message_counter})

        # update counter
        message_counter+=1
        
        results.append(result)

print("results: ", results)

KeyboardInterrupt:

In [6]:
results = []
for conversation in sample_conversations:
    message_counter = 1
    id = "sample_id"
    # printing response and metadata for one conversation
    for message in sample_conversation["messages"]:
        if message["role"]=="user":
            # output user's query
            query = message["content"]
            result = bot.answer_this(query=query)
            
            result.update({"query":query, "order": message_counter, "chat_id":id})

            # update counter
            message_counter+=1
            
            results.append(result)

results

[{'chatbot_response': 'Based on the information provided, there is no lab session scheduled for next week. The lab session for next week is intended for Mini-Project consultation, so there is no need to rush to complete any lab exercises. It is recommended to use the lab session to work on your mini project and consult your TA. If your mini project is progressing well, you can start working on the lab exercises. If you have any further questions or need clarification, feel free to ask.',
  'context': ['I wish you will enjoy the exercise and learn more through it, rather than just attempt it for the marks. As always, I will post the solution after the week 5 and after all submissions end (in case there are extensions).\xa0\n\nPlease note that LABS on Feb 9th is cancelled and will be done on Feb 16th. Affected lab groups please note.\n\nRegards,\nSmitha\n\nDS Theory quiz details , Exercise 4 posted\n\nPosted on: Thursday, February 15, 2024 2:07:10 PM SGT\n\nData Science Theory Quiz details have been posted under "Quizzes" section on NTULearn course site.\xa0The quiz will be held across 2 slots on\xa08 March, Friday: 12:30 pm - 2:00 pm and 2:30 pm - 4:00 pm.\xa0Please check the quiz slot and venue allocation carefully in that information, and come to the designated lab on time. For part time students, the session will be on 8 March, Friday, 7:00 pm - 8:30 pm @HPL.\n\nA make-up session will be held on week 8, 13th March, Wednesday, 4.30 pm - 5:30 pm (lecture hour), only to cater for the exceptional cases. Please refer to Quiz details posted under "Quizzes" tab.\n\nI have posted Exercise 4 (linear Regression) for next week.\xa0 Please feel free to discuss with your friends and your Lab TA if you have any problem.The solution to Exercise 3 and LAMS Quiz Answers for EDA (few more yet to complete the same) will be posted by early next week . I will also post the project details by early next week. \xa0\n\nregards,\n\nSmitha\n\nMini Project details released\n\nPosted on: Monday, February 19, 2024 5:38:22 PM SGT',
   "I have posted Exercise 4 (linear Regression) for next week.\xa0 Please feel free to discuss with your friends and your Lab TA if you have any problem.The solution to Exercise 3 and LAMS Quiz Answers for EDA (few more yet to complete the same) will be posted by early next week . I will also post the project details by early next week. \xa0\n\nregards,\n\nSmitha\n\nMini Project details released\n\nPosted on: Monday, February 19, 2024 5:38:22 PM SGT\n\nDear Students,\n\nHope you are enjoying Exercise 4 on Linear Regression this week. Please feel free to discuss with your friends and your Lab TA if you have any problem.\n\nWe have released the Mini Project details.\xa0Please check the Mini-Project Tab in NTUlearn Coursesite for more information. I have also suggested a few datasets. You may take a look at them, or find your own.\nFinding your own dataset/problem for your own project is still preferable. Use the suggested data sources only if you can't find any other dataset.\n\nYour Lab TAs will share a google speard sheet with you such that you can formally enter the team for the Mini Project. Please wait for the instructions from your LAB TAs.\xa0\n\nSee you for the review lecture on Wednesday on Classification/ Decision tree. :-)\n\nRegards,\nSmitha\n\nExercise 5 released, sign up sheet for mini project also released via LAB TAs\n\nPosted on: Wednesday, February 21, 2024 3:12:26 PM SGT\n\nDear Students,\n\nI have posted Exercise 5 under Lab Sessions on the NTULearn Course Site. It is on Classification Trees.",
   'Next Review Lecture & Lab Exercise 7\n\nLast but not least, we hope to see a higher turn-up rate in the upcoming Review Lecture (same link as the recent one) where I will cover Module 3 & brief the requirements for Lab Exercise 7. The handout will be released a few hours before the session itself. Do join using your NTU Email address so that you do not need to wait in the lobby.\n\nBest Regards & Have a great weekend ahead,\n\nOng Chin Ann\nLecturer | SC1015/CE1115/CZ1115\nchinann.ong@ntu.edu.sg\n\nLab Exercise 7 Released (5%)\n\nPosted on: Wednesday, March 20, 2024 10:13:17 AM SGT\n\nDear Students,\n\nGood Day & Good Morning!!! Just to poke and inform you that the requirements for\xa0Lab Exercise 7 (Graded)\xa0is now released and available under "Lab Session" menu.\n\nDo note that based on course calendar, the Lab Session for this weeks (Week 9) is intended for Mini-Project consultation, hence, there is\xa0no need for you to rush to complete the Lab Exercise 7\xa0on this week itself (because you are given plenty of allowance and time to complete it). You should make use of the lab session this week to work on your mini project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 7.\xa0\n\nDo plan your time and work with your team member effectively to complete this exercise. What I will suggest is:',
   'Today, we will talk about some of the main clarifications regarding Decision Trees that you may need to solve Exercise 5 next week.\xa0\n\nThe sign up sheets for min-project is released by your Lab TAs under your lab groups course site. Max size-3 members, Min size=2 members. Please sign up ASAP. If you have difficulty in forming the group, do talk to your TAs. The deadline for you to sign up and form teams is by\xa01st March Friday evening 5pm.\xa0\n\nOnly once the project groups are formed, you can officially start discussing about the same and i can also create peer evaluation portal for same.\n\nSee you today evening for the discussion lecture.\n\nregards\n\nSmitha\n\n[General] Up Next for Part 2 on DSAI!!!!\n\nPosted on: Saturday, March 9, 2024 3:30:00 PM SGT\n\nDear Students,\n\nHope all of you are doing well and are ready to move on to the second part of the course, Artificial Intelligence.\n\nFirst of all, the materials for\xa0Lab Exercise 6: Walk-Through Notebook\xa0(Ungraded) are now available. Do note that\xa0exercise 6\xa0is for your\xa0DS mini-project\xa0and not for the AI.\n\nIn addition to that, the\xa0LAMS Sequence and learning materials for the AI part\xa0are also made available now under the "Course Content" menu for your self-paced learning. The materials for\xa0Lab Exercise 7 (AI Graded Lab)\xa0will be released after next week.\xa0\n\nBelow are the main topics to be covered in the second half of this course :\n\nAI Module 1: Introduction and State-of-the-Art\n\nAI Module 2: Intelligent Agents',
   'In addition to that, the\xa0LAMS Sequence and learning materials for the AI part\xa0are also made available now under the "Course Content" menu for your self-paced learning. The materials for\xa0Lab Exercise 7 (AI Graded Lab)\xa0will be released after next week.\xa0\n\nBelow are the main topics to be covered in the second half of this course :\n\nAI Module 1: Introduction and State-of-the-Art\n\nAI Module 2: Intelligent Agents\n\nAI Module 3: Solving Problems by Search\n\nAI Module 4: Constraint Satisfaction and Game Playing\n\nDo note that these topics (AI Module 1- 4) will be assessed during the\xa0AI Theory Quiz (25%)\xa0at the end of the course.\nYou are advised to complete at least one module per week to catch up with the review lecture and lab exercises for AI.\xa0\nThere will be only\xa04 review lectures\xa0for AI which will be conducted on\xa013, 20, and 27 March\xa0as well as\xa03 April\xa0respectively. MS Team link will be announced at NTU Learn on the day itself. Lab Exercises for AI will be released progressively.'],
  'cost': 0.0033815,
  'tokens': 2223,
  'query': 'is there lab next week?',
  'order': 1,
  'chat_id': 'sample_id'},
 {'chatbot_response': "Today's date is 2024-09-19. Based on the information provided, we are currently in Week 14, which started from 22 April 2024. If you have any more questions or need further assistance, feel free to ask!",
  'context': ['Next Review Lecture & Lab Exercise 7\n\nLast but not least, we hope to see a higher turn-up rate in the upcoming Review Lecture (same link as the recent one) where I will cover Module 3 & brief the requirements for Lab Exercise 7. The handout will be released a few hours before the session itself. Do join using your NTU Email address so that you do not need to wait in the lobby.\n\nBest Regards & Have a great weekend ahead,\n\nOng Chin Ann\nLecturer | SC1015/CE1115/CZ1115\nchinann.ong@ntu.edu.sg\n\nLab Exercise 7 Released (5%)\n\nPosted on: Wednesday, March 20, 2024 10:13:17 AM SGT\n\nDear Students,\n\nGood Day & Good Morning!!! Just to poke and inform you that the requirements for\xa0Lab Exercise 7 (Graded)\xa0is now released and available under "Lab Session" menu.\n\nDo note that based on course calendar, the Lab Session for this weeks (Week 9) is intended for Mini-Project consultation, hence, there is\xa0no need for you to rush to complete the Lab Exercise 7\xa0on this week itself (because you are given plenty of allowance and time to complete it). You should make use of the lab session this week to work on your mini project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 7.\xa0\n\nDo plan your time and work with your team member effectively to complete this exercise. What I will suggest is:',
   "You MUST mention which dataset(s) you used, and what EXACTLY is your problem definition.\n\nThis is your chance to explain your MOTIVATION. Don't get carried away; be precise and clear.\n\nNext 3 minutes (approx.)\xa0of your presentation --\xa0Set The Stage\n\nPresent your Exploratory Data Analysis and some initial data-driven Insights from the dataset.\n\nYou MAY also mention how you are planning to set up the Analysis / ML problem for this case.\n\nYou MUST mention how you collected / curated / cleaned / prepared the data for this problem.\n\nDid you only use tools and techniques learned in this course? What ELSE did you learn / try?\n\nNext 3 minutes (approx.)\xa0of your presentation --\xa0Core Analysis\n\nIf you used ML (regression, classification, or something else); mention mainly WHICH one(s).\n\nYou may now briefly CLARIFY why and how the ML problem(s) aim(s) to solve your objective.\n\nHow did you apply ML technique(s) to SOLVE your problem? Which model(s), how and why?\n\nDid you only use tools and techniques learned in this course? What ELSE did you learn / try?\n\nLast 2 minutes (approx.)\xa0of your presentation --\xa0Finish Strong\n\nWhat is the OUTCOME of your project? Did it solve your original problem? Anything interesting?\n\nWhat are your data-driven INSIGHTS and recommendations / views towards the target problem?\n\nEverything you plan to showcase should be presented within the 10 mins. Plan carefully and smartly.",
   'P/S: For subsequent Review Lecture in Week 10 & 11, we will be using the same link.\n\nSee you all later, the more the merrier.\n\n\xa0\n\nBest Regards,\n\nOng Chin Ann\nLecturer (SC1015/CE1115/CZ1115)\nemail: chinann.ong@ntu.edu.sg\n\nDS quiz score released\n\nPosted on: Thursday, March 21, 2024 10:00:44 AM SGT\n\nDear Students,\n\nI have released the marks for DS Theory Quiz. The statistics are as follows.\n\nCount : 984 \xa0| \xa0Total marks : 30 \xa0| \xa0Mean : 18.93 \xa0| \xa0Median : 19.25 \xa0| \xa0StdDev : 4.33 \xa0| \xa0Max : 29.5 \xa0| \xa0Min : 3.5\xa0| \xa0Q1 : 16.25 \xa0| \xa0Q3 : 22\n\nIf you have any queries on your marks/quiz feel free to meet me in my office. Queries through email will not be entertained.\n\nRegards,\nSmitha\n\nLab Exercise 8 Released (5%)\n\nPosted on: Wednesday, April 3, 2024 9:06:35 AM SGT\n\nDear Students,\n\nGood Day & Good Morning!!!\n\nJust to post & inform you that the requirements for\xa0Lab Exercise 8 (Graded)\xa0is now released and available under the "Lab Session" menu.\n\nDo note that based on the course calendar, the Lab Session for this week (Week 11) is intended for Mini-Project consultation, hence, you are advise to make use of the lab session this week to work on your mini-project and consult your TA. If your mini project is progressing very well, then of course you can start working on Lab Exercise 8.\xa0\n\nDo plan your time and work with your team members effectively to complete this exercise. What I will suggest is:',
   'Q2.7 : Can I get an extension for the LAMS quizzes? I missed it because ...\n\nA : Really sorry. No extension for the LAMS embedded quizzes beyond the deadline, unless your case is truly exceptional. Feel free to send me an email if you think so, but please do note that in most common cases of missing the deadline, it will not be considered. Please try to finish the quizzes within the deadline, or much ahead of time, if possible, so that there is no last minute issue with submission, network outage or sync issues on NTULearn. Anyway, your deadlines are set to coincide with the theory quizzes, and under all practical circumstances, you should complete the LAMS quizzes during revision for your theory quizzes. So, I do not think you want to miss the deadlines. ;-)\n\nFAQs regarding Labs Sessions\n\nQ3.1 : What is the schedule for the Lab Sessions? My NTU calendar says something different.\n\nA : Lab Sessions will happen every week (almost), throughout the semester, and you will generally complete hand-on programming exercises (and some related discussions) during the sessions. They will be held at the Labs. Please check our Course Calendar for the final lab schedule, irrespective of what is mentioned in your NTU calendar. For example : There is no Lab Session in Week 1 or Week 5(the CNY week) and Week 13 (last week of classes).\n\nQ3.2 : What will we actually do in the Lab Sessions?',
   "Generally, every team should be a 3-member team. You can form 2-member teams only if your Lab Group is not a clean multiple of 3. Please talk to your Lab TA to finalize the project group. They will collect the exact project team information from you in Week 8, after the Recess Week. So you have time to decide on your group.\n\nEven if it's tempting, you can't unfortunately team-up with your Lab TA or with the Course Instructors. We have our own project groups. ;-)\n\nQ5.3 : What if I can't find a team? What if I don't have any friend in my Lab?\n\nA : Please talk to the Lab TA in such a case. They will help you pair up with teams that have 2 (TWO) members or less. Teams are not supposed to have 2 (TWO) members unless it is required for the Lab Group where the total number of students is not a clean multiple of 3. By Week 8, you and/or your TA will surely be able to find you a project team if you can't get it by yourself. Don't worry. Note that team of 4 (FOUR) members will not be allowed.\xa0\n\nQ5.4 : Does the Mini-Project test on Data Science or Artificial Intelligence too?"],
  'cost': 0.0032405000000000003,
  'tokens': 2143,
  'query': 'what week is it now',
  'order': 2,
  'chat_id': 'sample_id'},
 {'chatbot_response': "I'm sorry, I couldn't find specific information about the deadline for your assignment in the provided context. I recommend checking the course syllabus, assignment instructions, or reaching out to the course coordinator or instructors (smitha@ntu.edu.sg | chinann.ong@ntu.edu.sg) for clarification on the assignment deadline.",
  'context': ['Q2.7 : Can I get an extension for the LAMS quizzes? I missed it because ...\n\nA : Really sorry. No extension for the LAMS embedded quizzes beyond the deadline, unless your case is truly exceptional. Feel free to send me an email if you think so, but please do note that in most common cases of missing the deadline, it will not be considered. Please try to finish the quizzes within the deadline, or much ahead of time, if possible, so that there is no last minute issue with submission, network outage or sync issues on NTULearn. Anyway, your deadlines are set to coincide with the theory quizzes, and under all practical circumstances, you should complete the LAMS quizzes during revision for your theory quizzes. So, I do not think you want to miss the deadlines. ;-)\n\nFAQs regarding Labs Sessions\n\nQ3.1 : What is the schedule for the Lab Sessions? My NTU calendar says something different.\n\nA : Lab Sessions will happen every week (almost), throughout the semester, and you will generally complete hand-on programming exercises (and some related discussions) during the sessions. They will be held at the Labs. Please check our Course Calendar for the final lab schedule, irrespective of what is mentioned in your NTU calendar. For example : There is no Lab Session in Week 1 or Week 5(the CNY week) and Week 13 (last week of classes).\n\nQ3.2 : What will we actually do in the Lab Sessions?',
   'Warning : In quest for "quick impression", please do not try to "produce a film" with cool animations and stuff.\xa0That\'s not the point! ;-)\n\n\nQ5.13 : Who will grade my Mini-Project?\n\nThe Presentations will be graded by your own Lab\'s TA. The Instructors (Smitha and Ong Chin Ann) will NOT grade your project. Thus, it is imperative that you talk to your Lab TA. They will mentor you as well as grade your project.\n\n\nQ5.14 : What will I finally submit for the Mini-Project?\n\nYou will have to submit your\xa0Presentation Video, the PPT/PDF slides used for the Presentation, all your codes on Github (Jupyter Notebooks, Python codes, Visualization codes, etc.), with reference to the resources you used during the project. If you build an application, a visualization tool, a dashboard or a website, you may also submit the link to that. Your submission will be on NTULearn (the video), plus a link to your Github repository (for code and other materials).\n\nNote : Guidelines on Presentation and Submission of Project will be communicated closer to the deadline.\n\n\nQ5.15 : How is my "individual contribution" judged for the project?',
   'Please note that lab sessions for 9th FEB -friday (eve of CNY) is cancelled. The EX 3 lab for this classes (FCSA,FCS3,FCEB,FCS6,FDAB,FCSH) will be on Week 5 friday (16th Feb)\n\nRegards,\nSmitha\n\nSC1015: Exercise 3 for week 4 posted in NTUlearn\n\nPosted on: Friday, February 2, 2024 10:24:00 AM SGT\n\nDear Students,\n\nI have posted Exercise 3 on NTULearn (under "Lab Sessions").\xa0Note that this is a graded exercise, worth 5% of your total marks.\n\nThe grading will be done by your Lab TA. It is highly advisable to complete the work and submit the assignment before the end of lab session. Thus, I would recommend that you take a look at the exercise (or start attempting parts of it) before you go to the lab. You may always discuss the problems with your friends at the lab or with your TA if you have any doubt. The deadline for submission is within 2 hrs from the end time of your lab group session. (HARD Deadline).\n\nYou are\xa0allowed to submit the graded lab excersise only when you are present in the lab session. If you are absent for the graded lab excersise due to a valid reason (MC or letter of permission from school approving leave), then report to your TA and they will allow you to submit via email. Check FAQ for more details.',

In [7]:
df = pd.DataFrame(data=results)
df

,chatbot_response,context,cost,tokens,query,order,chat_id
0,"Based on the information provided, there is no...",[I wish you will enjoy the exercise and learn ...,0.003381,2223,is there lab next week?,1,sample_id
1,Today's date is 2024-09-19. Based on the infor...,[Next Review Lecture & Lab Exercise 7\n\nLast ...,0.003241,2143,what week is it now,2,sample_id
2,"I'm sorry, I couldn't find specific informatio...",[Q2.7 : Can I get an extension for the LAMS qu...,0.002846,1875,what is the deadline for my assignment,3,sample_id
3,"I'm sorry, I couldn't find specific informatio...",[Q2.7 : Can I get an extension for the LAMS qu...,0.002846,1875,what is the deadline for my assignment,4,sample_id

## Test with chatlog data

### Test chatbot function

In [8]:
print("Number of conversations: ", len(chatlog["chatlog"]))

Number of conversations:  791

In [18]:
# cut down to sample chatlog
sample_chatlog = chatlog["chatlog"][108]
sample_chatlog

{'_id': {'$oid': '65fa4e6f6090ad0b74002bf3'},
 'stime': {'text': '2024-03-20 10:48:15', 'timestamp': 1710902895.371987},
 'messages': [{'role': 'user',
   'content': 'Hi Narelle :)',
   'recorded_on': {'text': '2024-03-20 10:48:40',
    'timestamp': 1710902920.173479}},
  {'role': 'ai',
   'content': "Hello! How can I assist you today? \n\n\n **Sources:** *['Course Information', 'FAQs about the Course', 'NTU Learn - Announcements Page']*",
   'recorded_on': {'text': '2024-03-20 10:48:45',
    'timestamp': 1710902925.067538},
   'token_cost': {'cost': '0.00296550', 'tokens': 1974}},
  {'role': 'user',
   'content': 'How were you programmed?',
   'recorded_on': {'text': '2024-03-20 10:48:55',
    'timestamp': 1710902935.104551}},
  {'role': 'ai',
   'content': "I was programmed using natural language processing (NLP) techniques and machine learning algorithms. My developers used Python programming language and various libraries such as NLTK, spaCy, and TensorFlow to build my conversational abilities. They also trained me on a large dataset of conversations to improve my responses and make me more accurate. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Announcements Page', 'NTU Learn - Mini Project Page']*",
   'recorded_on': {'text': '2024-03-20 10:48:59',
    'timestamp': 1710902939.479759},
   'token_cost': {'cost': '0.00330150', 'tokens': 2180}},
  {'role': 'user',
   'content': "That's great! How can I help?",
   'recorded_on': {'text': '2024-03-20 10:49:17',
    'timestamp': 1710902957.161853}},
  {'role': 'ai',
   'content': "I'm glad you're willing to help! Is there anything specific you would like to contribute to the course or the chatbot development? If you're interested in RAG-based chatbot development, you can join the lecturer's team during the semester break (May-July 2024) to learn more and gain some experience with LLM & RAG. You can also email the course instructors or lab TAs if you have any questions or doubts regarding the course material. \n\n\n **Sources:** *['FAQs about the Course', 'NTU Learn - Announcements Page', 'NTU Learn - Mini Project Page']*",
   'recorded_on': {'text': '2024-03-20 10:49:21',
    'timestamp': 1710902961.275046},
   'token_cost': {'cost': '0.00324100', 'tokens': 2129}}],
 'last_interact': {'text': '2024-03-20 10:49:21',
  'timestamp': 1710902961.275295},
 'llm_deployment_name': 'asknarelle-experimental-gpt-35-turbo',
 'llm_model_name': 'gpt-3.5-turbo-instruct',
 'vectorstore_index': 'vector-sc1015-ay23t2-b',
 'overall_cost': {'overall_cost': 0.009507999999999999,
  'overall_tokens': 6283},
 'Person': '078a1b84005e3417f28792bcd0d80b2b'}

In [20]:
results = []
for conversation in sample_chatlog:
    id = conversation["_id"]['$oid']

    message_counter = 1

    # printing response and metadata for one conversation
    for message in conversation["messages"]:

        # generate chatbot response for each user message
        if message["role"]=="user":
            # output user's query
            query = message["content"]
            result = bot.answer_this(query=query)
            
            result.update({"query":query, "message_order": message_counter, "conversation_id":id})

            # update message counter
            message_counter+=1
            
            results.append(result)
    
    # clear chat history since conversation is over
    bot.clear_chat_history()


results

_id

TypeError: string indices must be integers, not 'str'

In [7]:
# convert results to dataframe
df = pd.DataFrame(data=results)

# reorder columns
ordered_columns = ['conversation_id', 'message_order', 'query','chatbot_response', 'context', 'cost', 'tokens' ]
df = df[ordered_columns]

df

,conversation_id,message_order,query,chatbot_response,context,cost,tokens
0,65f172e8192f78bab2a94539,1,is there lab next week?,The lab on February 9th is cancelled and will ...,I wish you will enjoy the exercise and learn m...,0.000311,2002
1,65f172e8192f78bab2a94539,2,what week is it now,"Currently, it is Week 3 of the course, which s...",Next Review Lecture & Lab Exercise 7\n\nLast b...,0.000352,2279
2,65f172e8192f78bab2a94539,3,what is the deadline for my assignment,The deadline for your graded lab exercise (Exe...,Please note that lab sessions for 9th FEB -fri...,0.000342,2091
3,65f172e8192f78bab2a94539,4,what is the deadline for my assignment,The deadline for your graded lab exercise (Exe...,Please note that lab sessions for 9th FEB -fri...,0.000352,2163
4,65f17301192f78bab2a9453c,1,what type of questions will I get in the AI th...,The AI Theory Quiz will consist of various typ...,You are allowed to use your Pen/Pencil and Cal...,0.000335,2057
5,65f17301192f78bab2a9453c,2,how should I study for the quiz,"To study for the quiz, I recommend the followi...",Course Information\n\n‘Data’ is the new drivin...,0.000519,2174
6,65f17302192f78bab2a9453d,1,when is my lab session?,"Sorry, I am unable to answer your question. I ...",The action set should not be more than or arou...,0.000294,1953
7,65f17302192f78bab2a9453d,2,when is exercise 5 due?,"Sorry, I am unable to answer your question. I ...",Please note that lab sessions for 9th FEB -fri...,0.000303,2013
8,65f17302192f78bab2a9453d,3,summarise module 1 of Artificial Intelligence,"Sorry, I am unable to answer your question. I ...",Artificial Intelligence : Theory Quiz\n\nArtif...,0.000340,2259

In [9]:
# export to csv

test_results_dir = "test_results"

df.to_csv(path_or_buf=test_results_dir+os.sep+"basic_indexing_results.csv", index=False)

### Test trivial query function

In [15]:
# cut down to sample chatlog
sample_chatlog = chatlog["chatlog"][107]
sample_chatlog

{'_id': {'$oid': '65fa4c816090ad0b74002bf1'},
 'stime': {'text': '2024-03-20 10:40:01', 'timestamp': 1710902401.612804},
 'messages': [{'role': 'user',
   'content': 'What is the requirements for the project in SC1015?',
   'recorded_on': {'text': '2024-03-20 10:40:29',
    'timestamp': 1710902429.832487}},
  {'role': 'ai',
   'content': "The requirements for the project in SC1015 are as follows:\n\n1. You will have to work in a group of 3 (THREE) students.\n2. You will have to come up with your own problem definition based on a dataset.\n3. You will have to prepare and clean the data to suit the problem of your choice.\n4. You will have to perform exploratory data analysis/visualization to gather relevant insights.\n5. You will have to use machine learning techniques to solve specific problems.\n6. You will have to present your project in a video format, following the guidelines provided.\n7. You will have to submit the entire codebase for your project in the form of a complete URL to your GitHub repository.\n\nPlease note that the project will primarily test you on Data Science, but will also extend into the realm of Machine Learning and things that you will learn on your own to apply. \n\n\n **Sources:** *['NTU Learn - Mini Project Page', 'FAQs about the Course', 'NTU Learn - Announcements Page', 'SC1015_BasicInformation']*",
   'recorded_on': {'text': '2024-03-20 10:40:36',
    'timestamp': 1710902436.388543},
   'token_cost': {'cost': '0.00397450', 'tokens': 2589}},
  {'role': 'user',
   'content': 'When will the grades of midterm be released?',
   'recorded_on': {'text': '2024-03-20 10:41:38',
    'timestamp': 1710902498.832143}},
  {'role': 'ai',
   'content': "I'm sorry, but there is no mention of a midterm in the information provided for the course SC1015/CE1115/CZ1115 - Introduction to Data Science & Artificial Intelligence. The course is graded based on continuous assessment, which includes lab exercises, theory quizzes, and a mini-project. The marks for some of the graded components will be disclosed during the semester, while others will only reflect in the final result. If you have any further questions regarding the grading or assessment of the course, please feel free to ask. ",
   'recorded_on': {'text': '2024-03-20 10:41:44',
    'timestamp': 1710902504.183988},
   'token_cost': {'cost': '0.00442900', 'tokens': 2917}}],
 'last_interact': {'text': '2024-03-20 10:41:44',
  'timestamp': 1710902504.184195},
 'llm_deployment_name': 'asknarelle-experimental-gpt-35-turbo',
 'llm_model_name': 'gpt-3.5-turbo-instruct',
 'vectorstore_index': 'vector-sc1015-ay23t2-b',
 'overall_cost': {'overall_cost': 0.0084035, 'overall_tokens': 5506},
 'Person': 'd7f261beb6a1241dd6c939256bc847e1'}

In [9]:
# convert results to dataframe
df = pd.DataFrame(data=results)

df.columns

Index(['is_trivial_query', 'chatbot_response', 'context', 'cost', 'tokens',
       'query', 'message_order', 'conversation_id'],
      dtype='object')

In [10]:
# reorder columns
ordered_columns = ['conversation_id', "message_order", "query", "is_trivial_query", "chatbot_response"]
df_ordered = df[ordered_columns]

df_ordered

,conversation_id,message_order,query,is_trivial_query,chatbot_response
0,65f172e8192f78bab2a94539,1,is there lab next week?,YES,"Based on the information provided, there is no..."
1,65f172e8192f78bab2a94539,2,what week is it now,NO,Today's date is 2024-09-19. Based on the infor...
2,65f172e8192f78bab2a94539,3,what is the deadline for my assignment,NO,"I'm sorry, I couldn't find specific informatio..."
3,65f172e8192f78bab2a94539,4,what is the deadline for my assignment,NO,"I'm sorry, I couldn't find specific informatio..."
4,65f17301192f78bab2a9453c,1,what type of questions will I get in the AI th...,NO,"In the AI Theory Quiz, you can expect to encou..."
5,65f17301192f78bab2a9453c,2,how should I study for the quiz,NO,To study for the quiz in the SC1015 Data Scien...
6,65f17302192f78bab2a9453d,1,when is my lab session?,YES,"I'm sorry, I would need more specific informat..."
7,65f17302192f78bab2a9453d,2,when is exercise 5 due?,YES,"Exercise 5 is due on Friday, February 16, 2024..."
8,65f17302192f78bab2a9453d,3,summarise module 1 of Artificial Intelligence,NO,Module 1 of Artificial Intelligence covers the...
9,65f17307192f78bab2a9453f,1,When is the AI Quiz?,NO,The AI Quiz will take place in Week 14 on Mond...
10,65f17307192f78bab2a9453f,2,When is the AI Quiz?,NO,The AI Quiz will take place in Week 14 on Mond...
11,65f17307192f78bab2a9453f,3,When will the DS Quiz results be released?,NO,"The DS Quiz results were released on Thursday,..."
12,65f17307192f78bab2a9453f,4,What is the DS Quiz average usually?,NO,The DS Quiz average usually contributes 15% to...
13,65f17307192f78bab2a9453f,5,Thank you very much!,NO,You're welcome! If you have any more questions...
14,65f17326192f78bab2a94544,1,hello,NO,Hello! How can I assist you today with the SC1...
15,65f17326192f78bab2a94544,2,when is the final quiz for 1015?,NO,The final quiz for SC1015 Data Science and Art...
16,65f17329192f78bab2a94545,1,hello,NO,Hello! How can I assist you today with the SC1...
17,65f17329192f78bab2a94545,2,hi,NO,Hello! How can I assist you today regarding th...
18,65f17329192f78bab2a94545,3,give me a summary of the AI part of the module,NO,The AI part of the module covers the following...
19,65f17329192f78bab2a94545,4,give me a quiz of introduction and state of th...,NO,I can provide you with a few sample multiple-c...
20,65f1732e192f78bab2a94547,1,hello!,NO,Hello! How can I assist you today with your qu...
21,65f1732e192f78bab2a94547,2,How do I join the development team for ask nar...,YES,"To join the development team for AskNarelle, y..."
22,65f1732e192f78bab2a94547,3,What technical knowledge do i need to do the c...,YES,"To develop a chatbot like ""AskNarelle,"" you wo..."
23,65f17333192f78bab2a94549,1,when is the ddl for the mini project?,YES,The deadline for the Mini-Project submission i...

In [10]:
# export to csv

test_results_dir = "test_results"

df_ordered.to_excel(test_results_dir+os.sep+"trivial_categorisation_results_4.xlsx", index=False)

## Test with test_cases

In [19]:
from test_cases import non_trivial_questions

# rephrased versions of "Will the Lab TAs teach new topics during the Lab Sessions?"
rephrased_qs = [
    "Will the TAs cover new material in the lab?",
    "Are lab sessions meant for learning new topics?",
    "Do the TAs introduce new concepts during labs?",
    "Will we learn anything new from the TAs in lab?",
    "Are new topics taught by TAs in lab sessions?",
    "Do lab sessions include teaching new material?",
    "Will the TAs explain new topics during the lab?",
    "Are labs designed to teach us new topics?",
    "Do lab TAs present new lessons or topics?",
    "Is new content covered in lab sessions?",
    "Do we learn fresh concepts in lab sessions?",
    "Will the lab sessions introduce new ideas?",
    "Do lab TAs go over new subject matter?",
    "Are labs focused on teaching new things?",
    "Will new material be discussed in lab sessions?"
]

test_cases = non_trivial_questions

test_cases

['When was this module created?',
 'Will the Lab TAs teach new topics during the Lab Sessions',
 'Will there be a final examination for the course?',
 'Why all the LAMS sequences are posted together, and not released per week?',
 'Will every LAMS sequence have graded embedded quiz?',
 'Will the LAMS quizzes be single-try or multiple-try questions?',
 'Will the LAMS embedded quizzes be available after the deadline?',
 'Can I sit with my acquaintance at the Lab?',
 'Will the Lab TAs teach new topics during the Lab Sessions?',
 'Do we need to make-up for a Lab Exercise that we miss?',
 'Do we need to make-up for a Lab Exercise that we miss?',
 'What if my teammates assess me unfairly for the project even if I contribute?',
 'What is the Grading Scheme for the Mini-Project?',
 "What is an 'interesting problem' based on the dataset for the mini project?",
 "What do you mean by 'data preparation and cleaning' for the mini project?"]

In [18]:
# test array of questions
results = []

for query in test_cases:
    result = {"question": query}

    # check original chatbot response
    chatbot_result = bot.answer_this(
        query=query
    )

    result.update(chatbot_result)

    results.append(result)

results

===== CONTEXT FOR QUERY 'When was this module created?' =====

Posted on: Friday, March 15, 2024 11:47:11 AM SGT

Dear Students,

Just to update you on a few points in case you missed out on our first review lecture on AI Part:

Review Lecture Recording

The recording for our AI review lecture on 13 March 2024 is now available under the "Course Media" section. During the review lecture, I highlighted a few key important points for Module 1 and Module 2. We also went through some live pop quizzes to make the session more lively and interactive.

Launching of LLM-powered RAG-AI Chatbot

Prior to the end of the session, I introduce attendees to the LLM-powered RAG-AI Chatbot, "AskNarelle" (https://asknarelle.azurewebsites.net/). This chatbot was developed as part of a research initiative to investigate the feasibility and effectiveness of incorporating Generative AI/LLM-based chatbot to enhance the student learning experience by getting swift responses for trivial queries regarding the course information. Currently, "Narelle" has been fed with knowledge/information (last update on 9 March 2024) about the SC1015 course structure and administration matters only. These knowledge/information includes the course outline, course assessments, FAQs, instructors/TA information, announcements at NTU Learn, and the course calendar. New information will be fed along the way.

---------------
You DO NOT need to show your faces in the presentation, but you may of course show faces, if you want. Please speak yourselves in the video; DO NOT use a robo-voiceover.

The presentation is primarily through PPT/PDF/Google Slides, plus some portion of your Jupyter Notebooks and workflow to describe parts of the project, as and when required.

You DO NOT need to show raw code during the presentation. You may show pieces of your code, if you think that is important. Otherwise, mainly show results and observations.

If you are planning to go back-and-forth between your slides and the notebooks (to show code or visualizations), manage your time carefully and make sure you touch all points.

Good sample videos for inspiration would be SCSE Final Year Project videos available on SCSE Marketing YouTube channel : https://www.youtube.com/c/SCSEMarketing/videos

Do not panic over the actual content presented in the FYP videos. They worked for one whole year, and that too, in the final year. We are not expecting the same from you now. ;-)

You will also find sample video presentations from the last time this course was offered under "Course Content > Review Sessions". They had 7 minutes, while you have 10 mins.

---------------
Hence, we encourage and welcome all of you to try it out when you have questions regarding the course. In other words, when you have question(s) about the course, you can try to ask "Narelle" first, before approaching/emailing your TA or Instructor. You can also help us to evaluate the relevancy/correctness of the responses by pressing the "Thumbs Up/Down" under each response. Do tell us what you think about the chatbot a few weeks later after you have interacted with the chatbot or when you come across some error with the chatbot by clicking the "Feedback" button on the left panel, we will look into it and fix it.

Do note that at present time, we have not fed "Narelle" with any course contents e.g. textbook or lecture slides/materials used in this course. But you can give it a try by asking questions related to the course syllabus/content to see how it behaves/responds (we are also interested to know how it behaves too :) ). Do read through the remote informed consent and terms of use before using the Chatbot.

Getting Involved in the Research & Development for AskNarelle - Ungraded Activity

---------------
Item 2 : Entire Codebase for your Project, in the form of a COMPLETE URL to your GitHub repository.
Input the URL to your GitHub repository in the "Text Field" available in the portal for the aforesaid Video.
Your TA will open a single portal for you to upload your video; your URL must also be provided alongwith.

This codebase should contain your codes/notebooks and data files, as required, for the complete project.
The repo may tentatively follow the structure and flow of examples under "Video Presentation Guidelines".
The repo must include a decently composed README file for your TA to read and understand the project.
It is unlikely that your TA will execute your codes for every single project, but they will read the README.
You may include a copy of your slides that you used in the video presentation (not mandatory) in the repo.

ONE submission portal will be created for the Video and the Codebase -- under your own LabGroup Course Site.

Your TA will create these submission portals by April 16th, and you can submit unlimited number of times before the deadline.

The last submission before the deadline will be graded. Please make sure you submit only ONE video for your entire team.

If you have any technical issue with the submission of your video, please talk to your TA directly; they will control the portal.

Make sure you submit BOTH the MP4 file for the Video presentation and the GitHub URL in text format; we will need both.

Guidelines for Video Presentation

---------------
In addition to that, the LAMS Sequence and learning materials for the AI part are also made available now under the "Course Content" menu for your self-paced learning. The materials for Lab Exercise 7 (AI Graded Lab) will be released after next week.

Below are the main topics to be covered in the second half of this course :

AI Module 1: Introduction and State-of-the-Art

AI Module 2: Intelligent Agents

AI Module 3: Solving Problems by Search

AI Module 4: Constraint Satisfaction and Game Playing

Do note that these topics (AI Module 1- 4) will be assessed during the AI Theory Quiz (25%) at the end of the course.
You are advised to complete at least one module per week to catch up with the review lecture and lab exercises for AI.
There will be only 4 review lectures for AI which will be conducted on 13, 20, and 27 March as well as 3 April respectively. MS Team link will be announced at NTU Learn on the day itself. Lab Exercises for AI will be released progressively.
===================




===== CONTEXT FOR QUERY 'Will the Lab TAs teach new topics during the Lab Sessions' =====

Question: Who taught this course in 2020?
Answer: Mr. A

Question: Can I email the school to S/U this course?
Answer: Yes, you may email su_ntu@gmail.com to S/U this course.

Question: Question2
Answer: hi

Question: Will the Lab TAs teach new topics during the Lab Sessions
Answer: No. There will be no formal lecture or teaching during the Lab Sessions. The main course material is just the LAMS sequences, videos and respective slides. The labs are meant for hands-on programming, and the codes that you work on will be tested through the Lab Exercises. However, your Lab TAs may introduce you to some new material every week while they recap the main ideas behind the respective Lab Exercise. These will not be examinable.

---------------
Clear and precise/specific. Not too simple nor too complex

N/A

IMPORTANT NOTE ON THIS LAB EXERCISE

This lab exercise is to be completed in groups (same members as the mini-project). - one submission per group

The deadline for this lab is 3 days after the respective lab session (including weekend & public holiday).

Your group should not select topics such as Maze Runner/Solver as a sample has been provided.

Avoid Tic-Tac-Toe topic as we will discuss on that in Lab Exercise 8

The topic should not be too simple nor overly complicated as you will implement the agent with search tree in Lab Exercise 8 later. The tree will typically represent the states of the agent's environment

Some guides/points for topic selection:


Look for some online mini-game websites to explore and select a game/puzzle.

the number of environment states should be between 20 - 120 states which can be constructed as a tree.

Choose a single-player game/puzzle rather than two or multi-player game/puzzle.

The action set should not be more than or around 10.

You must attend the Graded Lab session (Lab Exercise 7) to be eligible to earn the marks for your group work. If you are absent with valid reason, your team member will have to acknowledge that you have participated/contributed to the work and subsequently give consent to TA for them to award you the mark. There will be no make up lab.

My personal message to all students

---------------
Clear presentation, on time (5 mins, ±30 secs), smooth flow of the presentation, but nothing much special or interesting

Excellent presentation, on time (5 mins, ±30 secs), very clear, smooth flow of presentation, and very interesting and engaging.

Participation & Teamwork
(0.5%) - Video

No cam on, very minimal intro

Cam on but not all member introduce themself or the other way round

Cam on, all member introduce themself

N/A

IMPORTANT NOTE ON THIS LAB EXERCISE

This lab exercise is to be completed in groups (same members as the mini-project) - one submission per group.

The deadline for this lab is 3 days after the respective lab session (including weekend & public holiday).

Your group should not implement topics such as Maze Runner/Solver / Tic-Tac-Toe as a sample has been provided. Do consult your TA to get another topic.

You must attend the Graded Lab session (Lab Exercise 8) to be eligible to earn the marks for your group work. If you are absent with valid reason, your team member will have to acknowledge that you have participated/contributed to the work and subsequently give consent to TA for them to award you the mark. There will be no make up lab.

Remember my personal message to all students posted in Lab Exercise 7.
“Your integrity determines your destiny.” – Heraclitus

---------------
As a group, try to solve the problems among your group first. Take help and hints from the LAMS on Modules 1 & 2. If you are still stuck, talk to your TA in the Lab Session to get help/hints. Feel free to discuss with your classmates too.

Remember, this exercise is for your learning and experience, not just for the sake of 5%. Your future along with the knowledge, skill (technical/soft), and experience gained through participation in this exercise is worth more than the 5%.
Happy trying and I do hope all of you learn something new by attempting this exercise.

Cheers,

Ong Chin Ann

Exercise 8 : Agent Implementation with Search (Group)

Attached Files:

 Sample-Search Algorithm.ipynb  (665.54 KB)

 Sample-Minimax.ipynb  (38.521 KB)

Submission is required for this Exercise. It is worth 5% of your grade.
Please check with your Lab Instructor or TA on how to submit your Solution.

Objectives:

In this exercise, you will see uninformed search algorithms like breadth_first_search, depth_first_search and uniform_cost_search, as well as informed search algorithms like greedy_search and astar_search in action. The sample provided is a maze with the problem of finding an escape path from the start position to the goal position on a two-dimensional grid (based on the problem formulation provided previously). You will observe how to map a maze (two-dimensional grid) to a graph, and then apply the search algorithms on the graph to solve the problem.

---------------
Correctly identify all dimensions of the environment with clear descriptions/examples

Definition of selected problem
(1%)

The problem definition is vague

problem definition is clear but the scope might be too broad or overly simple

Clear and precise/specific. Not too simple nor too complex

Clear and precise/specific Not too simple nor too complex

With good and appropriate illustration

Specification
(1.5%)

Correctly identify some but not all specification

Correctly describe all specifications without much elaboration.

Correctly describe all specifications but some parts are unclear (a bit hard to understand).

Correctly describe all specifications, clear, and effective.

Definition of Solution
(0.5%)

The solution definition is vague

problem definition is acceptable/moderate but the scope might be too broad or overly simple

Clear and precise/specific. Not too simple nor too complex

N/A

IMPORTANT NOTE ON THIS LAB EXERCISE

This lab exercise is to be completed in groups (same members as the mini-project). - one submission per group

The deadline for this lab is 3 days after the respective lab session (including weekend & public holiday).

Your group should not select topics such as Maze Runner/Solver as a sample has been provided.

Avoid Tic-Tac-Toe topic as we will discuss on that in Lab Exercise 8
===================




===== CONTEXT FOR QUERY 'Will there be a final examination for the course?' =====

Course Resources

There is no single textbook for this course. We will follow the references from time to time. Additional resources, if required, will be shared with you in the Lectures and/or in the Lab.

References

Python Data Science Handbook by Jake Vanderplas (https://jakevdp.github.io/PythonDataScienceHandbook/)

An Introduction to Statistical Learning by James, Witten, Hastie, Tibshirani (https://statlearning.com/)

Artificial Intelligence: A Modern Approach by Stuart Russell and Peter Norvig (http://aima.cs.berkeley.edu/)

Course and Lab Instructors

Dr Smitha K G, Senior Lecturer, SCSE, and Mr. Ong Chin Ann, Lecturer , SCSE are the Instructors for this course.  You will also interact with them during the Review sessions. Dr Smitha K G  (smitha@ntu.edu.sg) is the Course Coordinator.

Please note that your LAMS sequences were earlier prepared by Dr. Sourav Sen Gupta (DS) and Prof. Bo. An (AI).

Course Instructors

Dr Smitha K G (Co-Ord) and Mr. Ong Chin Ann

smitha@ntu.edu.sg

chinann.ong@ntu.edu.sg

Office : N4-02c-75

Office : N4-02c-108

---------------
The course will motivate you to work closely with data and make data-driven decisions in your field of study. The course will also touch upon ethical issues in Data Science and Artificial Intelligence, and motivate you to explore the cutting-edge applications related to Big Data, Neural Networks and Deep Learning. Python will be the language of choice to introduce hands-on computational techniques.

By the end of this course, you should be able to identify and define data-oriented problems and data-driven decisions in real life, discuss and illustrate the problems in terms of data exploration and visualization, apply basic machine learning tools to extract inferential information from the data, compose an engaging “data-story” to communicate the problem and the inference, outline the roles and requirements of artificial intelligence in practical applications, apply basic artificial intelligence techniques in search problems and game playing, and discuss and explain concepts of computer vision and natural language processing.

Course Resources

There is no single textbook for this course. We will follow the references from time to time. Additional resources, if required, will be shared with you in the Lectures and/or in the Lab.

References

Python Data Science Handbook by Jake Vanderplas (https://jakevdp.github.io/PythonDataScienceHandbook/)

An Introduction to Statistical Learning by James, Witten, Hastie, Tibshirani (https://statlearning.com/)

---------------
You DO NOT need to show your faces in the presentation, but you may of course show faces, if you want. Please speak yourselves in the video; DO NOT use a robo-voiceover.

The presentation is primarily through PPT/PDF/Google Slides, plus some portion of your Jupyter Notebooks and workflow to describe parts of the project, as and when required.

You DO NOT need to show raw code during the presentation. You may show pieces of your code, if you think that is important. Otherwise, mainly show results and observations.

If you are planning to go back-and-forth between your slides and the notebooks (to show code or visualizations), manage your time carefully and make sure you touch all points.

Good sample videos for inspiration would be SCSE Final Year Project videos available on SCSE Marketing YouTube channel : https://www.youtube.com/c/SCSEMarketing/videos

Do not panic over the actual content presented in the FYP videos. They worked for one whole year, and that too, in the final year. We are not expecting the same from you now. ;-)

You will also find sample video presentations from the last time this course was offered under "Course Content > Review Sessions". They had 7 minutes, while you have 10 mins.

---------------
Do not panic over the actual content presented in the FYP videos. They worked for one whole year, and that too, in the final year. We are not expecting the same from you now. ;-)

You will also find sample video presentations from the last time this course was offered under "Course Content > Review Sessions". They had 7 minutes, while you have 10 mins.

Examples of some nice project presentations from the previous year are as follows. Please do not copy the ideas or share them, as they belong to the students who did the work. Note that the example projects presented below are not ordered in terms of quality or any other parameter. They are just to provide you with three very different styles of approaching the Mini-Project. You need not do everything that these projects have attempted, but you may surely take note of the work these groups put into the project, and how much they learned on their own. I am sure you will do great as well. :-) Link: https://ntulearn.ntu.edu.sg/ultra/courses/_2650965_1/cl/outline




How should we structure the GitHub Code Repository?

Your entire codebase for the project should be posted on GitHub. You will submit the link to us.
Note that you DO NOT need to collaborate on GitHub. Posting your final codes will be enough.

Some instructions that you may follow for the GitHub repository:

Make sure all your codes/notebooks plus the data is on the repository for the TA to check.

---------------
Course Information

‘Data’ is the new driving force, provided we know how to extract relevant ‘Intelligence’.

This course will start with the core principles of Data Science, and will equip you with the basic tools and techniques of data handling, exploratory data analysis, data visualization, data-based inference, and data-focussed communication. The course will also introduce you to the fundamentals of Artificial Intelligence – state space, search problems, computer vision and natural language processing.

The course will motivate you to work closely with data and make data-driven decisions in your field of study. The course will also touch upon ethical issues in Data Science and Artificial Intelligence, and motivate you to explore the cutting-edge applications related to Big Data, Neural Networks and Deep Learning. Python will be the language of choice to introduce hands-on computational techniques.
===================




===== CONTEXT FOR QUERY 'Why all the LAMS sequences are posted together, and not released per week?' =====

ANNOUNCEMENTS

Updated on: 08 April 2024

Welcome to SC1015 Introduction to DS and AI

Posted on: Monday, January 15, 2024 12:31:19 PM SGT

Dear Students,

Wish you a very Happy New Year 2024. Welcome to SC1015 : Introduction to Data Science and Artificial Intelligence.

Mr. Ong Chin Ann and Dr Smitha K G (that's me) will be your Course Instructors this time. I am also the Course Co-ordinator.

Few important points about the course before we begin ...

This course runs entirely on LAMS sequences + Review Lectures (online, once a week) + the Lab Sessions (2 hours per week).

The schedule of the course will follow the Course Calendar posted under "Information", irrespective of your NTU calendar says.

This means that there will be NO Lab Sessions in Week 1, Week 5 (CNY week) and Week 13 -- even if NTU calendar says so.


[{'question': 'When was this module created?',
  'chatbot_response': 'The AI Module was created for the second half of the SC1015 Data Science and Artificial Intelligence course.',
  'context': 'Posted on: Friday, March 15, 2024 11:47:11 AM SGT\n\nDear Students,\n\nJust to update you on a few points in case you missed out on our first review lecture on AI Part:\n\nReview Lecture Recording\n\nThe recording for our AI review lecture on 13 March 2024 is now available under the "Course Media" section. During the review lecture, I highlighted a few key important points for Module 1 and Module 2. We also went through some live pop quizzes to make the session more lively and interactive.\n\nLaunching of LLM-powered RAG-AI Chatbot\n\nPrior to the end of the session, I introduce attendees to the LLM-powered RAG-AI Chatbot, "AskNarelle"\xa0(https://asknarelle.azurewebsites.net/). This chatbot was developed as part of a research initiative to investigate the feasibility and effectiveness of incorporating Generative AI/LLM-based chatbot to enhance the student learning experience by getting swift responses for trivial queries regarding the course information. Currently, "Narelle" has been fed with knowledge/information (last update on 9 March 2024) about the SC1015 course structure and administration matters only. These knowledge/information includes the course outline, course assessments, FAQs, instructors/TA information, announcements at NTU Learn, and the course calendar. New information will be fed along the way.\n\n---------------\nYou DO NOT need to show your faces in the presentation, but you may of course show faces, if you want. Please speak yourselves in the video; DO NOT use a robo-voiceover.\n\nThe presentation is primarily through PPT/PDF/Google Slides, plus some portion of your Jupyter Notebooks and workflow to describe parts of the project, as and when required.\n\nYou DO NOT need to show raw code during the presentation. You may show pieces of your code, if you think that is important. Otherwise, mainly show results and observations.\n\nIf you are planning to go back-and-forth between your slides and the notebooks (to show code or visualizations), manage your time carefully and make sure you touch all points.\n\nGood sample videos for inspiration would be SCSE Final Year Project videos available on SCSE Marketing YouTube channel :\xa0https://www.youtube.com/c/SCSEMarketing/videos\n\nDo not panic over the actual content presented in the FYP videos. They worked for one whole year, and that too, in the final year. We are not expecting the same from you now. ;-)\n\nYou will also find sample video presentations from the last time this course was offered under "Course Content > Review Sessions". They had 7 minutes, while you have 10 mins.\n\n---------------\nHence, we encourage and welcome all of you to try it out when you have questions regarding the course. In other words, when you have question(s) about the course, you can try to ask "Narelle" first, before approaching/emailing your TA or Instructor. You can also help us to evaluate the relevancy/correctness of the responses by pressing the "Thumbs Up/Down" under each response. Do tell us what you think about the chatbot a few weeks later after you have interacted with the chatbot or when you come across some error with the chatbot by clicking the "Feedback" button on the left panel, we will look into it and fix it.\n\nDo note that at present time, we have not fed "Narelle" with any course contents e.g. textbook or lecture slides/materials used in this course. But you can give it a try by asking questions related to the course syllabus/content to see how it behaves/responds (we are also interested to know how it behaves too :) ). Do read through the remote informed consent and terms of use before using the Chatbot.\n\nGetting Involved in the Research & Development for AskNarelle - Ungraded Activity\n\n---------------\nItem 2 : Entire Codebase for your Project, in the form of a COMPLETE URL to your GitHub repository.\nInput the URL to your GitHub repository in the\xa0"Text Field"\xa0available in the portal for the aforesaid Video.\nYour TA will open a single portal for you to upload your video; your URL must also be provided alongwith.\n\nThis codebase should contain your codes/notebooks and data files, as required, for the complete project.\nThe repo may tentatively follow the structure and flow of examples under "Video Presentation Guidelines".\nThe repo must include a decently composed README file for your TA to read and understand the project.\nIt is unlikely that your TA will execute your codes for every single project, but they will read the README.\nYou may include a copy of your slides that you used in the video presentation (not mandatory) in the repo.\n\nONE submission portal will be created for the Video and the Codebase -- under your own LabGroup Course Site.\n\nYour TA will create these submission portals by April 16th, and you can submit unlimited number of times before the deadline.\n\nThe last submission before the deadline will be graded. Please make sure you submit only ONE video for your entire team.\n\nIf you have any technical issue with the submission of your video, please talk to your TA directly; they will control the portal.\n\nMake sure you submit BOTH the MP4 file for the Video presentation and the GitHub URL in text format; we will need both.\n\nGuidelines for Video Presentation\n\n---------------\nIn addition to that, the\xa0LAMS Sequence and learning materials for the AI part\xa0are also made available now under the "Course Content" menu for your self-paced learning. The materials for\xa0Lab Exercise 7 (AI Graded Lab)\xa0will be released after next week.\xa0\n\nBelow are the main topics to be covered in the second half of this course :\n\nAI Module 1: Introduction and State-of-the-Art\n\nAI Module 2: Intelligent Agents\n\nAI Module 3: Solving Problems by Search\n\nAI Module 4: Constraint Satisfaction and Game Playing\n\nDo note that these topics (AI Module 1- 4) will be assessed during the\xa0AI Theory Quiz (25%)\xa0at the end of the course.\nYou are advised to complete at least one module per week to catch up with the review lecture and lab exercises for AI.\xa0\nThere will be only\xa04 review lectures\xa0for AI which will be conducted on\xa013, 20, and 27 March\xa0as well as\xa03 April\xa0respectively. MS Team link will be announced at NTU Learn on the day itself. Lab Exercises for AI will be released progressively.',
  'cost': 0.002523,
  'tokens': 1675},
 {'question': 'Will the Lab TAs teach new topics during the Lab Sessions',
  'chatbot_response': 'No. There will be no formal lecture or teaching during the Lab Sessions. The main course material is just the LAMS sequences, videos, and respective slides. The labs are meant for hands-on programming, and the codes that you work on will be tested through the Lab Exercises. However, your Lab TAs may introduce you to some new material every week while they recap the main ideas behind the respective Lab Exercise. These will not be examinable.',
  'context': "Question: Who taught this course in 2020?\nAnswer: Mr. A\n\nQuestion: Can I email the school to S/U this course?\nAnswer: Yes, you may email su_ntu@gmail.com to S/U this course.\n\nQuestion: Question2\nAnswer: hi\n\nQuestion: Will the Lab TAs teach new topics during the Lab Sessions\nAnswer: No. There will be no formal lecture or teaching during the Lab Sessions. The main course material is just the LAMS sequences, videos and respective slides. The labs are meant for hands-on programming, and the codes that you work on will be tested through the Lab Exercises. However, your Lab TAs may introduce you to some new material every week while they recap the main ideas behind the respective Lab Exercise. These will not be examinable.\n\n---------------\nClear and precise/specific. Not too simple nor too complex\n\nN/A\n\nIMPORTANT NOTE ON THIS LAB EXERCISE\n\nThis lab exercise is to be completed\xa0in groups\xa0(same members as the mini-project). - one submission per group\n\nThe deadline for this lab is\xa03 days\xa0after the respective lab session (including weekend & public holiday).\n\nYour group should not select topics such as\xa0Maze Runner/Solver\xa0as a sample has been provided.\xa0\n\nAvoid\xa0Tic-Tac-Toe\xa0topic as we will discuss on that in Lab Exercise 8\n\nThe topic should not be too simple nor overly complicated as you will implement the agent with search tree in\xa0Lab Exercise 8\xa0later. The tree will typically represent the states of the agent's environment\n\nSome guides/points for topic selection:\n\n\nLook for some online mini-game websites to explore and select a game/puzzle.\n\nthe number of environment states should be between 20 - 120 states which can be constructed as a tree.\n\nChoose a single-player game/puzzle rather than two or multi-player game/puzzle.\n\nThe action set should not be more than or around 10.\n\nYou\xa0must attend the Graded Lab session (Lab Exercise 7)\xa0to be eligible to earn the marks for your group work. If you are absent with valid reason, your team member will have to acknowledge that you have participated/contributed to the work and subsequently give consent to TA for them to award you the mark. There will be no make up lab.\n\nMy personal message to all students\n\n---------------\nClear presentation, on time (5 mins, ±30 secs), smooth flow of the presentation, but nothing much special or interesting\n\nExcellent presentation, on time (5 mins, ±30 secs), very clear, smooth flow of presentation, and very interesting and engaging.\n\nParticipation & Teamwork\n(0.5%) - Video\n\nNo cam on, very minimal intro\n\nCam on but not all member introduce themself or the other way round\n\nCam on, all member introduce themself\n\nN/A\n\nIMPORTANT NOTE ON THIS LAB EXERCISE\n\nThis lab exercise is to be completed\xa0in groups\xa0(same members as the mini-project) - one submission per group.\n\nThe deadline for this lab is\xa03 days\xa0after the respective lab session (including weekend & public holiday).\n\nYour group should not implement topics such as\xa0Maze Runner/Solver\xa0/\xa0Tic-Tac-Toe\xa0as a sample has been provided. Do consult your TA to get another topic.\n\nYou\xa0must attend the Graded Lab session (Lab Exercise 8)\xa0to be eligible to earn the marks for your group work. If you are absent with valid reason, your team member will have to acknowledge that you have participated/contributed to the work and subsequently give consent to TA for them to award you the mark. There will be no make up lab.\n\nRemember my personal message to all students posted in Lab Exercise 7.\n“Your integrity determines your destiny.” – Heraclitus\n\n---------------\nAs a group, try to solve the problems among your group first. Take help and hints from the LAMS on Modules 1 & 2. If you are still stuck, talk to your TA in the Lab Session to get help/hints. Feel free to discuss with your classmates too.\n\nRemember, this exercise is for your learning and experience, not just for the sake of 5%. Your future along with the knowledge, skill (technical/soft), and experience gained through participation in this exercise is worth more than the 5%.\nHappy trying and I do hope all of you learn something new by attempting this exercise.\n\nCheers,\n\nOng Chin Ann\n\nExercise 8 : Agent Implementation with Search (Group)\n\nAttached Files:\n\n\xa0Sample-Search Algorithm.ipynb\xa0\xa0(665.54 KB)\n\n\xa0Sample-Minimax.ipynb\xa0\xa0(38.521 KB)\n\nSubmission is required for this Exercise. It is worth 5% of your grade.\nPlease check with your Lab Instructor or TA on how to submit your Solution.\n\nObjectives:\n\nIn this exercise, you will see uninformed search algorithms like breadth_first_search, depth_first_search and uniform_cost_search, as well as informed search algorithms like greedy_search and astar_search in action. The sample provided is a maze with the problem of finding an escape path from the start position to the goal position on a two-dimensional grid (based on the problem formulation provided previously). You will observe how to map a maze (two-dimensional grid) to a graph, and then apply the search algorithms on the graph to solve the problem.\n\n---------------\nCorrectly identify all dimensions of the environment with clear descriptions/examples\n\nDefinition of selected problem\n(1%)\n\nThe problem definition is vague\n\nproblem definition is clear but the scope might be too broad or overly simple\n\nClear and precise/specific. Not too simple nor too complex\n\nClear and precise/specific Not too simple nor too complex\n\nWith good and appropriate illustration\n\nSpecification\n(1.5%)\n\nCorrectly identify some but not all specification\n\nCorrectly describe all specifications without much elaboration.\n\nCorrectly describe all specifications but some parts are unclear (a bit hard to understand).\n\nCorrectly describe all specifications, clear, and effective.\n\nDefinition of Solution\n(0.5%)\n\nThe solution definition is vague\n\nproblem definition is acceptable/moderate but the scope might be too broad or overly simple\n\nClear and precise/specific. Not too simple nor too complex\n\nN/A\n\nIMPORTANT NOTE ON THIS LAB EXERCISE\n\nThis lab exercise is to be completed\xa0in groups\xa0(same members as the mini-project). - one submission per group\n\nThe deadline for this lab is\xa03 days\xa0after the respective lab session (including weekend & public holiday).\n\nYour group should not select topics such as\xa0Maze Runner/Solver\xa0as a sample has been provided.\xa0\n\nAvoid\xa0Tic-Tac-Toe\xa0topic as we will discuss on that in Lab Exercise 8",
  'cost': 0.0027215,
  'tokens': 1784},
 {'question': 'Will there be a final examination for the course?',
  'chatbot_response': 'There will not be a final examination for the course SC1015 Data Science and Artificial Intelligence. The assessment will be based on assignments, projects, tests, and quizzes throughout the duration of the course.',

In [20]:
# convert results to dataframe
df = pd.DataFrame(data=results)

df

,question,chatbot_response,context,cost,tokens
0,When was this module created?,The AI Module was created for the second half ...,"Posted on: Friday, March 15, 2024 11:47:11 AM ...",0.002523,1675
1,Will the Lab TAs teach new topics during the L...,No. There will be no formal lecture or teachin...,Question: Who taught this course in 2020?\nAns...,0.002721,1784
2,Will there be a final examination for the course?,There will not be a final examination for the ...,Course Resources\n\nThere is no single textboo...,0.002515,1663
3,Why all the LAMS sequences are posted together...,The reason all the LAMS sequences for the AI p...,ANNOUNCEMENTS\n\nUpdated on: 08 April 2024\n\n...,0.003231,2125
4,Will every LAMS sequence have graded embedded ...,"Sorry, I am unable to answer your question. I ...","In addition to that, the LAMS Sequence and lea...",0.002877,1917
5,Will the LAMS quizzes be single-try or multipl...,The LAMS quizzes will be single-try questions.,Quiz Instructions\n\nThis is a Closed-Book No-...,0.003019,2009
6,Will the LAMS embedded quizzes be available af...,The LAMS embedded quizzes will not be availabl...,Below are some important announcements and ite...,0.003230,2141
7,Can I sit with my acquaintance at the Lab?,"Yes, you can sit with your acquaintance at the...",The action set should not be more than or arou...,0.002949,1952
8,Will the Lab TAs teach new topics during the L...,No. There will be no formal lecture or teachin...,Question: Who taught this course in 2020?\nAns...,0.002723,1785
9,Do we need to make-up for a Lab Exercise that ...,You must attend the Graded Lab session (Lab Ex...,Prepare a Video (.mp4) of around 5 minutes or ...,0.002949,1940
10,Do we need to make-up for a Lab Exercise that ...,You must attend the Graded Lab session (Lab Ex...,Prepare a Video (.mp4) of around 5 minutes or ...,0.002949,1940
11,What if my teammates assess me unfairly for th...,If you feel that your teammates are assessing ...,Note that the AI Theory Quiz (25%) and Project...,0.003211,2107
12,What is the Grading Scheme for the Mini-Project?,The grading scheme for the Mini-Project will l...,Did you only use tools and techniques learned ...,0.003017,1972
13,What is an 'interesting problem' based on the ...,An interesting problem for the mini project co...,"You MUST mention which dataset(s) you used, an...",0.002984,1968
14,What do you mean by 'data preparation and clea...,"Sorry, I am unable to answer your question. I ...",Did you only use tools and techniques learned ...,0.002959,1971

In [15]:
# export to csv

test_results_dir = "test_results"

df.to_excel(test_results_dir+os.sep+"_non-trivial-q1.xlsx", index=False)